/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-12-28: 12h:54m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/stdio.cats"

#include "libc/sys/CATS/types.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_2 ;
ats_size_type atslab_3 ;
} anairiats_rec_1 ;

typedef
struct {
ats_ptr_type atslab_data ;
ats_size_type atslab_size ;
ats_size_type atslab_pos ;
ats_size_type atslab_posmax ;
} anairiats_rec_2 ;

/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size_int) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size_size) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size_size) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_mod1_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_char_type, atspre_string_get_char_at) (ats_ptr_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_string_make_substring) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_string_append) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_string_append) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_size_type, atspre_string_length) (ats_ptr_type) ;
ATSextern_fun(ats_size_type, atspre_string_length) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_elt_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ArraySubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e11_2prelude_2SATS_2array0_2esats__array0_make_arrpsz) (anairiats_rec_1) ;
ATSextern_fun(ats_ptr_type, atspre_matrix_ptr_takeout_row_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_matrix_ptr_takeout_elt_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_matrix_make_arrpsz__main) (ats_size_type, ats_size_type, anairiats_rec_1) ;
ATSextern_fun(ats_ptr_type, atspre_matrix_make_funenv_tsz) (ats_size_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e11_2prelude_2SATS_2matrix0_2esats__matrix0_make_arrpsz__main) (ats_size_type, ats_size_type, anairiats_rec_1) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2arith_2esats__mul_istot_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2arith_2esats__mul_isfun_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2arith_2esats__mul_nat_nat_nat_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2matrix_2esats__array_v_of_matrix_v_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2matrix_2esats__matrix_v_of_array_v_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2matrix0_2edats__lemma_for_matrix_subscripting_prfck () ;
extern
ats_void_type _2home_2brand_000_2FBA_2FALCON_2sstream_2edats__static_mystring_size_prfck () ;
extern
ats_void_type _2home_2brand_000_2FBA_2FALCON_2sstream_2edats__static_size1_size_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sasp__sstream = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_size_type mystr0_length_0 (ats_ptr_type arg0) ;
static
ats_size_type mystr1_length_1 (ats_ptr_type arg0) ;
static
ats_ptr_type mystr_substr_2 (ats_ptr_type arg0, ats_size_type arg1, ats_size_type arg2) ;
static
ats_ptr_type mystring_append_3 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type mystring1_append_4 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
anairiats_rec_2 strstream_make_5 (ats_ptr_type arg0, ats_size_type arg1) ;
static
ats_ptr_type ref_01087_anairiats_rec_2 (anairiats_rec_2 arg0) ;
static
ats_void_type sstream_testsz_13 (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 945(line=42, offs=4) -- 1006(line=42, offs=65)
*/
ATSstaticdec()
ats_size_type
mystr0_length_0 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_size_type, tmp0) ;

__ats_lab_mystr0_length_0:
tmp0 = atspre_string_length (arg0) ;
return (tmp0) ;
} /* end of [mystr0_length_0] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 1010(line=43, offs=4) -- 1103(line=43, offs=97)
*/
ATSstaticdec()
ats_size_type
mystr1_length_1 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_size_type, tmp1) ;

__ats_lab_mystr1_length_1:
tmp1 = atspre_string_length (arg0) ;
return (tmp1) ;
} /* end of [mystr1_length_1] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 1191(line=48, offs=4) -- 1413(line=53, offs=4)
*/
ATSstaticdec()
ats_ptr_type
mystr_substr_2 (ats_ptr_type arg0, ats_size_type arg1, ats_size_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_size_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab_mystr_substr_2:
tmp3 = mystr1_length_1 (arg0) ;
tmp4 = atspre_string_make_substring (arg0, arg1, arg2) ;
tmp2 = ats_castfn_mac(ats_ptr_type, tmp4) ;
return (tmp2) ;
} /* end of [mystr_substr_2] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 1796(line=68, offs=4) -- 1881(line=70, offs=26)
*/
ATSstaticdec()
ats_ptr_type
mystring_append_3 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp5) ;

__ats_lab_mystring_append_3:
tmp5 = atspre_string_append (arg0, arg1) ;
return (tmp5) ;
} /* end of [mystring_append_3] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 1918(line=73, offs=4) -- 2053(line=75, offs=46)
*/
ATSstaticdec()
ats_ptr_type
mystring1_append_4 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;

__ats_lab_mystring1_append_4:
tmp7 = atspre_string_append (arg0, arg1) ;
tmp6 = ats_castfn_mac(ats_ptr_type, tmp7) ;
return (tmp6) ;
} /* end of [mystring1_append_4] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 2424(line=95, offs=5) -- 2662(line=101, offs=4)
*/
ATSstaticdec()
anairiats_rec_2
strstream_make_5 (ats_ptr_type arg0, ats_size_type arg1) {
/* local vardec */
ATSlocal (anairiats_rec_2, tmp8) ;
ATSlocal (ats_size_type, tmp9) ;
ATSlocal (ats_size_type, tmp10) ;

__ats_lab_strstream_make_5:
tmp9 = mystr1_length_1 (ats_castfn_mac(ats_ptr_type, arg0)) ;
tmp10 = atspre_size1_of_int1 (0) ;
tmp8.atslab_data = ats_castfn_mac(ats_ptr_type, arg0) ;
tmp8.atslab_size = tmp9 ;
tmp8.atslab_pos = tmp10 ;
tmp8.atslab_posmax = ats_castfn_mac(ats_size_type, arg1) ;

return (tmp8) ;
} /* end of [strstream_make_5] */

/*
// /home/brand_000/ats-lang-anairiats-0.2.11/prelude/DATS/reference.dats: 1828(line=57, offs=18) -- 1902(line=59, offs=4)
*/
ATSstaticdec()
ats_ptr_type
ref_01087_anairiats_rec_2 (anairiats_rec_2 arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (anairiats_rec_2, tmp13) ;

__ats_lab_ref_01087_anairiats_rec_2:
/* anairiats_rec_2 tmp13 ; */
tmp13 = arg0 ;
tmp12 = atspre_ref_make_elt_tsz ((&tmp13), sizeof(anairiats_rec_2)) ;
return (tmp12) ;
} /* end of [ref_01087_anairiats_rec_2] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 2754(line=110, offs=14) -- 2848(line=111, offs=51)
*/
ATSglobaldec()
ats_ptr_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_make (ats_ptr_type arg0, ats_size_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (anairiats_rec_2, tmp14) ;

__ats_lab__2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_make:
tmp14 = strstream_make_5 (arg0, arg1) ;
tmp11 = ref_01087_anairiats_rec_2 (tmp14) ;
return (tmp11) ;
} /* end of [_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_make] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 2874(line=115, offs=13) -- 2942(line=117, offs=4)
*/
ATSglobaldec()
ats_size_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_pos (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_size_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;

__ats_lab__2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_pos:
tmp16 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp15 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp16), atslab_pos) ;
return (tmp15) ;
} /* end of [_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_pos] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 2993(line=121, offs=13) -- 3133(line=125, offs=4)
*/
ATSglobaldec()
ats_char_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_get (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_char_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_bool_type, tmp20) ;
ATSlocal (ats_size_type, tmp21) ;
ATSlocal (ats_size_type, tmp22) ;
ATSlocal (ats_size_type, tmp23) ;

__ats_lab__2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_get:
tmp18 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp19 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp18), atslab_data) ;
tmp21 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp18), atslab_pos) ;
tmp22 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp18), atslab_size) ;
tmp20 = atspre_lt_size1_size1 (tmp21, tmp22) ;
if (tmp20) {
tmp23 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp18), atslab_pos) ;
tmp17 = atspre_string_get_char_at (tmp19, tmp23) ;
} else {
tmp17 = '\000' ;
} /* end of [if] */
return (tmp17) ;
} /* end of [_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_get] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 3187(line=129, offs=13) -- 3297(line=132, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_inc (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_bool_type, tmp26) ;
ATSlocal (ats_size_type, tmp27) ;
ATSlocal (ats_size_type, tmp28) ;
ATSlocal (ats_size_type, tmp29) ;
ATSlocal (ats_size_type, tmp30) ;

__ats_lab__2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_inc:
tmp25 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp27 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp25), atslab_pos) ;
tmp28 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp25), atslab_size) ;
tmp26 = atspre_lt_size1_size1 (tmp27, tmp28) ;
if (tmp26) {
tmp30 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp25), atslab_pos) ;
tmp29 = atspre_add_size1_int1 (tmp30, 1) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp25), atslab_pos) = tmp29 ;
} else {
/* empty */
} /* end of [if] */
return /* (tmp24) */ ;
} /* end of [_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_inc] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 3326(line=135, offs=16) -- 3579(line=142, offs=4)
*/
ATSglobaldec()
ats_char_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_getinc (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_char_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_char_type, tmp34) ;
ATSlocal (ats_bool_type, tmp35) ;
ATSlocal (ats_size_type, tmp36) ;
ATSlocal (ats_size_type, tmp37) ;
ATSlocal (ats_size_type, tmp38) ;
ATSlocal (ats_bool_type, tmp40) ;
ATSlocal (ats_size_type, tmp41) ;
ATSlocal (ats_size_type, tmp42) ;
ATSlocal (ats_size_type, tmp43) ;
ATSlocal (ats_size_type, tmp44) ;

__ats_lab__2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_getinc:
tmp32 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp33 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp32), atslab_data) ;
tmp36 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp32), atslab_pos) ;
tmp37 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp32), atslab_size) ;
tmp35 = atspre_lt_size1_size1 (tmp36, tmp37) ;
if (tmp35) {
tmp38 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp32), atslab_pos) ;
tmp34 = atspre_string_get_char_at (tmp33, tmp38) ;
} else {
tmp34 = '\000' ;
} /* end of [if] */
tmp41 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp32), atslab_pos) ;
tmp42 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp32), atslab_size) ;
tmp40 = atspre_lt_size1_size1 (tmp41, tmp42) ;
if (tmp40) {
tmp44 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp32), atslab_pos) ;
tmp43 = atspre_add_size1_int1 (tmp44, 1) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp32), atslab_pos) = tmp43 ;
} else {
/* empty */
} /* end of [if] */
tmp31 = tmp34 ;
return (tmp31) ;
} /* end of [_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_getinc] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 3605(line=146, offs=14) -- 3674(line=149, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_read (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;

__ats_lab__2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_read:
tmp46 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp45 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp46), atslab_data) ;
return (tmp45) ;
} /* end of [_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_read] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 3707(line=151, offs=5) -- 3843(line=154, offs=11)
*/
ATSstaticdec()
ats_void_type
sstream_testsz_13 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;

__ats_lab_sstream_testsz_13:
tmp48 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
return /* (tmp47) */ ;
} /* end of [sstream_testsz_13] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 3870(line=158, offs=15) -- 4833(line=183, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_write (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_size_type, tmp51) ;
ATSlocal (ats_bool_type, tmp53) ;
ATSlocal (ats_size_type, tmp54) ;
ATSlocal (ats_bool_type, tmp55) ;
ATSlocal (ats_size_type, tmp56) ;
ATSlocal (ats_size_type, tmp57) ;
ATSlocal (ats_size_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_size_type, tmp61) ;
ATSlocal (ats_size_type, tmp62) ;
ATSlocal (ats_size_type, tmp63) ;
ATSlocal (ats_size_type, tmp64) ;
ATSlocal (ats_size_type, tmp65) ;
ATSlocal (ats_size_type, tmp66) ;
ATSlocal (ats_size_type, tmp67) ;
ATSlocal (ats_size_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_size_type, tmp71) ;
ATSlocal (ats_size_type, tmp72) ;

__ats_lab__2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_write:
tmp50 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp51 = mystr1_length_1 (arg1) ;
tmp54 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_posmax) ;
tmp53 = atspre_gt_size1_int1 (tmp54, 0) ;
if (tmp53) {
tmp57 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_pos) ;
tmp56 = atspre_add_size1_size1 (tmp57, tmp51) ;
tmp58 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_posmax) ;
tmp55 = atspre_gt_size1_size1 (tmp56, tmp58) ;
if (tmp55) {
tmp60 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_data) ;
tmp61 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_pos) ;
tmp63 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_size) ;
tmp64 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_pos) ;
tmp62 = atspre_sub_size1_size1 (tmp63, tmp64) ;
tmp59 = mystr_substr_2 (tmp60, tmp61, tmp62) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_data) = tmp59 ;
tmp66 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_size) ;
tmp67 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_pos) ;
tmp65 = atspre_sub_size1_size1 (tmp66, tmp67) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_size) = tmp65 ;
tmp68 = atspre_size1_of_int1 (0) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_pos) = tmp68 ;
} else {
/* empty */
} /* end of [if] */
} else {
/* empty */
} /* end of [if] */
tmp70 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_data) ;
tmp69 = mystring1_append_4 (tmp70, arg1) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_data) = tmp69 ;
tmp72 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_size) ;
tmp71 = atspre_add_size1_size1 (tmp72, tmp51) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp50), atslab_size) = tmp71 ;
return /* (tmp49) */ ;
} /* end of [_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_write] */

/*
// /home/brand_000/FBA/FALCON/sstream.dats: 4887(line=187, offs=16) -- 5224(line=198, offs=6)
*/
ATSglobaldec()
ats_ptr_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_substr (ats_ptr_type arg0, ats_size_type arg1, ats_size_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_size_type, tmp75) ;
ATSlocal (ats_bool_type, tmp76) ;
ATSlocal (ats_size_type, tmp77) ;
ATSlocal (ats_size_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;

__ats_lab__2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_substr:
tmp74 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp75 = atspre_sub_size_size (arg2, arg1) ;
tmp77 = atspre_add_size1_size1 (ats_castfn_mac(ats_size_type, arg1), ats_castfn_mac(ats_size_type, tmp75)) ;
tmp78 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp74), atslab_size) ;
tmp76 = atspre_lte_size1_size1 (tmp77, tmp78) ;
if (tmp76) {
tmp79 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_2, tmp74), atslab_data) ;
tmp73 = mystr_substr_2 (tmp79, ats_castfn_mac(ats_size_type, arg1), ats_castfn_mac(ats_size_type, tmp75)) ;
} else {
tmp73 = ATSstrcst("") ;
} /* end of [if] */
return (tmp73) ;
} /* end of [_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__sstream_substr] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e11_2libc_2SATS_2stdio_2esats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array0_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list0_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2matrix_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2matrix0_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2option_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2option0_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2pointer_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2reference_2edats__staload (void) ;
extern ats_void_type _2home_2brand_000_2FBA_2FALCON_2sstream_2esats__staload (void) ;

ats_void_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2edats__staload () {
static int _2home_2brand_000_2FBA_2FALCON_2sstream_2edats__staload_flag = 0 ;
if (_2home_2brand_000_2FBA_2FALCON_2sstream_2edats__staload_flag) return ;
_2home_2brand_000_2FBA_2FALCON_2sstream_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e11_2libc_2SATS_2stdio_2esats__staload () ;
// ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array0_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list0_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2matrix_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2matrix0_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2option_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2option0_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2pointer_2edats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2reference_2edats__staload () ;
_2home_2brand_000_2FBA_2FALCON_2sstream_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2brand_000_2FBA_2FALCON_2sstream_2edats__dynload_flag ;

ats_void_type
_2home_2brand_000_2FBA_2FALCON_2sstream_2edats__dynload () {
_2home_2brand_000_2FBA_2FALCON_2sstream_2edats__dynload_flag = 1 ;
_2home_2brand_000_2FBA_2FALCON_2sstream_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2arith_2esats__mul_istot_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2arith_2esats__mul_isfun_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2arith_2esats__mul_nat_nat_nat_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2matrix_2esats__array_v_of_matrix_v_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2matrix_2esats__matrix_v_of_array_v_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2matrix0_2edats__lemma_for_matrix_subscripting_prfck () ;
_2home_2brand_000_2FBA_2FALCON_2sstream_2edats__static_mystring_size_prfck () ;
_2home_2brand_000_2FBA_2FALCON_2sstream_2edats__static_size1_size_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [sstream_dats.c] */
