%This function finds all the reactions associated with a list of missing genes
function [geneList rxnList rxnNames rxnSubsys]=findMissingGenes(rec2, missingGenes)

%INPUT
%rec2 is the human recon 2 model 
%misssingGenes is a cell array containg one row and columns that each 
%contain cell arrays of all the missing genes associated with a particular
%subsystem. It can be generated by using the function analyzeSubsystemEnrichment 
%(missingGenesMRNA or missingGenesProtein)
%OUTPUT
%rxnList is a vector containing all the reaction numbers associated with the genes
%rxnNames is a cell array containing all the reaction names associated with the genes
%geneList is a cell array containing all the genes
%Narayanan Sadagopan September 2013

rxnList(1) = 0;  %all the reaction numbers associated with the genes		
rxnNames{1} = '';  %all the reaction names associated with the genes
geneList{1} = '';  %list of all the missing genes
rxnSubsys{1} = ''; %list of subsystem of reactions

%get all genes into a single cell array
temp{1} = 0;
count = 1;
for x = 1:length(missingGenes)
    for y = 1:length(missingGenes{1,x})
        temp{count} = missingGenes{1,x}{y};
        count = count + 1;
    end
end

%removes duplicate genes
geneList{1} = temp{1};
count = 2;
for x = 2:length(temp)
    truth =0 ;
    for y = 1:length(geneList)
        if (strcmp(geneList{y}, temp{x}))
            truth = 1;
        end
    end
    if (truth == 0)
        geneList{count} = temp{x};
        count = count + 1;
    end
end

%find rxns associated with the genes
count = 1;
temp2(1) = 0;
temp3{1} = 0;
for x = 1:length(geneList)
    for y = 1:length(rec2.genes(:))
        if (strcmp(rec2.genes{y}, geneList{x}))
            for z = 1:length(rec2.rxns(:))
                if (rec2.rxnGeneMat(z,y))
                    temp2(count) =z;
                    temp3{count} = rec2.rxnNames(z);
                    count = count + 1;
                end
            end
        end
    end
end

%remove duplicate rxns. Note not all "missing rxns" may actually 
%be missing because of and/or gene rules 
rxnList(1) = temp2(1);
rxnNames{1} = temp3{1};
count = 2;
for x = 1:length(temp2)
    truth = 0;
    for y = 1:length(rxnList)
        if (rxnList(y) == temp2(x))
            truth = 1;
        end
    end
    if (truth == 0)
        rxnList(count) = temp2(x);
        rxnNames{count} = temp3{x};
	 count = count + 1;
    end
end

%find associated subsystems
for x = 1:length(rxnList)
    rxnSubsys{x} = rec2.subSystems(rxnList);
end
        

        
        
    