% permuted experimental correlation distribution
if figName == 'pExp'
	plotSmoothHistPairs(PearsonExpVec75, PearsonExpVec85,              ...
		['Predictions for actual versus permuted expression:' char(10) ...
		'experimental flux correlation'] ,                             ...
		'Pearson''s r', 0.9879, '75% Max Growth', 0.9664, '85% Max Growth')
end

% permuted flux correlation distribution
if figName == 'kVvv'
	plotSmoothHistPairs(KendallVec75, KendallVec85,        ...
		['Flux vector correlation with fluxes' char(10)    ...
		'derived from permuted expression'], 'Kendall''s tau')
end
if figName == 'pVvv'
	plotSmoothHistPairs(PearsonVec75, PearsonVec85,        ...
		['Flux vector correlation with fluxes' char(10)    ...
		'derived from permuted expression'], 'Pearson''s r')
end