/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-4-17: 16h:22m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 1839(line=58, offs=1) -- 1879(line=58, offs=41)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/string.sats: 1380(line=35, offs=1) -- 1419(line=37, offs=3)
*/

#include "libc/CATS/string.cats"
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 13966(line=737, offs=1) -- 13996(line=737, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/stream.dats: 1564(line=46, offs=1) -- 1603(line=46, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/stream_vt.dats: 1567(line=46, offs=1) -- 1606(line=46, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 1647(line=47, offs=1) -- 1693(line=47, offs=47)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_parser.dats: 148(line=14, offs=1) -- 197(line=15, offs=42)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_parser.dats: 198(line=16, offs=1) -- 255(line=17, offs=50)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream_tokener.sats: 1600(line=37, offs=1) -- 1624(line=37, offs=25)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream_tokener.sats: 1649(line=41, offs=1) -- 1691(line=42, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/libats/SATS/stringbuf.sats: 1593(line=42, offs=1) -- 1637(line=44, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_parser.dats: 259(line=19, offs=1) -- 299(line=19, offs=41)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1607(line=42, offs=1) -- 1646(line=43, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1650(line=45, offs=1) -- 1687(line=46, offs=30)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1688(line=47, offs=1) -- 1728(line=48, offs=33)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1753(line=52, offs=1) -- 1792(line=53, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1815(line=57, offs=1) -- 1853(line=58, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1876(line=62, offs=1) -- 1912(line=62, offs=37)
*/
/*
/home/brand_000/ATS-Postiats/libats/SATS/stringbuf.sats: 1593(line=42, offs=1) -- 1637(line=44, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_parser.dats: 300(line=20, offs=1) -- 361(line=20, offs=62)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/DATS/cstream_tokener.dats: 1600(line=37, offs=1) -- 1639(line=38, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/DATS/cstream_tokener.dats: 1664(line=42, offs=1) -- 1696(line=42, offs=33)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/DATS/cstream_tokener.dats: 1697(line=43, offs=1) -- 1737(line=43, offs=41)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream_tokener.sats: 1600(line=37, offs=1) -- 1624(line=37, offs=25)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream_tokener.sats: 1649(line=41, offs=1) -- 1691(line=42, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/libats/SATS/stringbuf.sats: 1593(line=42, offs=1) -- 1637(line=44, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_parser.dats: 388(line=24, offs=1) -- 411(line=24, offs=24)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_parser.dats: 436(line=28, offs=1) -- 467(line=28, offs=32)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_tokener.dats: 148(line=14, offs=1) -- 184(line=14, offs=37)
*/
/*
/home/brand_000/ATS-Postiats/libats/SATS/stringbuf.sats: 1593(line=42, offs=1) -- 1637(line=44, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_tokener.dats: 185(line=15, offs=1) -- 234(line=15, offs=50)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_tokener.dats: 235(line=16, offs=1) -- 292(line=16, offs=58)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream_tokener.sats: 1600(line=37, offs=1) -- 1624(line=37, offs=25)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream_tokener.sats: 1649(line=41, offs=1) -- 1691(line=42, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/libats/SATS/stringbuf.sats: 1593(line=42, offs=1) -- 1637(line=44, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_tokener.dats: 296(line=18, offs=1) -- 336(line=18, offs=41)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1607(line=42, offs=1) -- 1646(line=43, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1650(line=45, offs=1) -- 1687(line=46, offs=30)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1688(line=47, offs=1) -- 1728(line=48, offs=33)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1753(line=52, offs=1) -- 1792(line=53, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1815(line=57, offs=1) -- 1853(line=58, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/libats/DATS/stringbuf.dats: 1876(line=62, offs=1) -- 1912(line=62, offs=37)
*/
/*
/home/brand_000/ATS-Postiats/libats/SATS/stringbuf.sats: 1593(line=42, offs=1) -- 1637(line=44, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_tokener.dats: 337(line=19, offs=1) -- 390(line=19, offs=54)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/DATS/cstream.dats: 1597(line=37, offs=1) -- 1636(line=38, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/DATS/cstream.dats: 1659(line=42, offs=1) -- 1691(line=42, offs=33)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_tokener.dats: 391(line=20, offs=1) -- 452(line=20, offs=62)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/DATS/cstream_tokener.dats: 1600(line=37, offs=1) -- 1639(line=38, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/DATS/cstream_tokener.dats: 1664(line=42, offs=1) -- 1696(line=42, offs=33)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/DATS/cstream_tokener.dats: 1697(line=43, offs=1) -- 1737(line=43, offs=41)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream_tokener.sats: 1600(line=37, offs=1) -- 1624(line=37, offs=25)
*/
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream.sats: 1597(line=37, offs=1) -- 1627(line=37, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/contrib/libats-hwxi/cstream/SATS/cstream_tokener.sats: 1649(line=41, offs=1) -- 1691(line=42, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/libats/SATS/stringbuf.sats: 1593(line=42, offs=1) -- 1637(line=44, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_tokener.dats: 479(line=24, offs=1) -- 502(line=24, offs=24)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_tokener.dats: 527(line=28, offs=1) -- 559(line=28, offs=33)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_position.dats: 110(line=12, offs=1) -- 133(line=12, offs=24)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_parser.dats: 3225(line=179, offs=1) -- 3267(line=180, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/strings.sats: 1380(line=35, offs=1) -- 1420(line=37, offs=3)
*/

#include "libc/CATS/strings.cats"
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize.dats: 146(line=14, offs=1) -- 169(line=14, offs=24)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize.dats: 194(line=18, offs=1) -- 233(line=19, offs=32)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize.dats: 256(line=23, offs=1) -- 289(line=23, offs=34)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/math.sats: 1380(line=35, offs=1) -- 1417(line=37, offs=3)
*/

#include "libc/CATS/math.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_0 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_1 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstype_boxed atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_2 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_3 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_4 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int_sub_int)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_mac(atspre_g0int_lt_int)
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_is_member, (atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_mac(atspre_fprint_string)
ATSdyncst_mac(atspre_FILE_stderr)
ATSdyncst_mac(atspre_fprint_int)
ATSdyncst_mac(atspre_fprint_newline)
ATSdyncst_mac(atspre_neg_bool0)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grexp_cnfize, (atstype_boxed), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__fprint_grcnf, (atstkind_type(atstype_ptrk), atsrefarg0_type(atstkind_type(atstype_ptrk))), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 739(line=51, offs=1) -- 773(line=51, offs=35)
*/
ATSassume(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_type) ;
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_int)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__compare_elt_elt__0(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_make_nil() ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_make_nil__2() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_make_nil__2__1() ;

#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_is_member(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_is_member__5(atstkind_type(atstype_ptrk), atstyvar_type(a), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstkind_t0ype(atstype_bool)
loop_6__6(atstyvar_type(a), atstype_funptr, atstype_boxed) ;
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_is_member__5__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstype_cloptr) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
loop_6__6__1(atstkind_t0ype(atstype_int), atstype_funptr, atstype_boxed) ;

ATSstaticdec()
atstkind_t0ype(atstype_int)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__compare_elt_elt__0__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_cloptr) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__11(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__11__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__15(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__15__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atstype_boxed
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__grexplst_cnfize_ifnot(atstype_boxed, atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstype_boxed
loop_19(atstkind_type(atstype_ptrk), atstype_boxed, atstkind_t0ype(atstype_int), atstype_boxed) ;

#if(0)
#if(0)
ATSglobaldec()
atstype_boxed
ATSLIB_056_prelude__list_vt_reverse__21(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstype_boxed
ATSLIB_056_prelude__list_vt_reverse__21__1(atstype_boxed) ;

#if(0)
#if(0)
ATSglobaldec()
atstype_boxed
ATSLIB_056_prelude__list_vt_reverse_append__23(atstype_boxed, atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
loop_24__24(atstype_boxed, atstype_boxed) ;
#endif // end of [TEMPLATE]

ATSstaticdec()
atstype_boxed
ATSLIB_056_prelude__list_vt_reverse_append__23__1(atstype_boxed, atstype_boxed) ;

ATSstaticdec()
atstype_boxed
loop_24__24__1(atstype_boxed, atstype_boxed) ;

typedef struct
{
atstype_funptr cfun ;
atstkind_t0ype(atstype_int) env0 ;
atstype_funptr env1 ;
} loop_6__6__1__closure_t0ype ;
ATSstaticdec()
atstkind_t0ype(atstype_bool)
loop_6__6__1__cfun
(
loop_6__6__1__closure_t0ype *p_cenv, atstype_boxed arg0
)
{
ATSFCreturn(loop_6__6__1(p_cenv->env0, p_cenv->env1, arg0)) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
loop_6__6__1__closureinit
(
loop_6__6__1__closure_t0ype *p_cenv, atstkind_t0ype(atstype_int) env0, atstype_funptr env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = loop_6__6__1__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
loop_6__6__1__closurerize
(
atstkind_t0ype(atstype_int) env0, atstype_funptr env1
)
{
return loop_6__6__1__closureinit(ATS_MALLOC(sizeof(loop_6__6__1__closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */

#if(0)
/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 870(line=58, offs=26) -- 887(line=58, offs=43)
*/
/*
local: 
global: compare_elt_elt$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = 
tmparg = S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__compare_elt_elt__0(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 845(line=58, offs=1) -- 887(line=58, offs=43)
*/
__patsflab_compare_elt_elt:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 882(line=58, offs=38) -- 887(line=58, offs=43)
*/
ATSINSmove(tmpret0, PMVtmpltcst(g0int_sub<S2Eextkind(atstype_int)>)(arg0, arg1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__compare_elt_elt__0] */
#endif // end of [TEMPLATE]

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 915(line=61, offs=17) -- 946(line=61, offs=48)
*/
/*
local: 
global: ruleset_make_nil$1$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_make_nil()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 899(line=61, offs=1) -- 946(line=61, offs=48)
*/
__patsflab_ruleset_make_nil:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 920(line=61, offs=22) -- 946(line=61, offs=48)
*/
ATSINSmove(tmpret1, _057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_make_nil__2__1()) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret1) ;
} /* end of [_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_make_nil] */

#if(0)
/*
/home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 2055(line=68, offs=17) -- 2071(line=68, offs=33)
*/
/*
local: 
global: funset_make_nil$2$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_make_nil__2()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 2039(line=68, offs=1) -- 2071(line=68, offs=33)
*/
__patsflab_funset_make_nil:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 2060(line=68, offs=22) -- 2071(line=68, offs=33)
*/

ATSINSmove_con0(tmpret2, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret2) ;
} /* end of [_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_make_nil__2] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 2055(line=68, offs=17) -- 2071(line=68, offs=33)
*/
/*
local: 
global: funset_make_nil$2$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_make_nil__2__1()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 2039(line=68, offs=1) -- 2071(line=68, offs=33)
*/
__patsflab_funset_make_nil:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 2060(line=68, offs=22) -- 2071(line=68, offs=33)
*/

ATSINSmove_con0(tmpret2__1, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret2__1) ;
} /* end of [_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_make_nil__2__1] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 976(line=64, offs=19) -- 1019(line=64, offs=62)
*/
/*
local: 
global: ruleset_is_member$4$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstkind_t0ype(atstype_bool)
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_is_member(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 958(line=64, offs=1) -- 1019(line=64, offs=62)
*/
__patsflab_ruleset_is_member:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 986(line=64, offs=29) -- 1019(line=64, offs=62)
*/
ATSINSmove(tmpret4, _057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_is_member__5__1(arg0, arg1, ATSPMVcastfn(cast, atstype_cloptr, ATSPMVi0nt(0)))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret4) ;
} /* end of [_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_is_member] */

#if(0)
/*
/home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3611(line=151, offs=3) -- 4048(line=176, offs=4)
*/
/*
local: 
global: funset_is_member$5$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(7399)
tmparg = S2Evar(a(7399))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_is_member__5(atstkind_type(atstype_ptrk) arg0, atstyvar_type(a) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3592(line=150, offs=1) -- 4048(line=176, offs=4)
*/
__patsflab_funset_is_member:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3627(line=151, offs=19) -- 4048(line=176, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 4035(line=175, offs=3) -- 4043(line=175, offs=11)
*/
ATSINSmove(tmpret5, ATSfunclo_clo(PMVd2vfunlab(d2v=loop$3136(1), flab=loop_6$0(level=1)), (atstype_cloptr, atstype_boxed), atstkind_t0ype(atstype_bool))(PMVd2vfunlab(d2v=loop$3136(1), flab=loop_6$0(level=1)), arg0)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3627(line=151, offs=19) -- 4048(line=176, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret5) ;
} /* end of [_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_is_member__5] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3638(line=153, offs=5) -- 4006(line=172, offs=2)
*/
/*
local: loop_6$0(level=1)
global: loop_6$0(level=1)
local: x0$3134(1)(HSEtyvar(a(7399))), cmp$3135(1)(HSEfun(HSEtyvar(a(7399)), HSEtyvar(a(7399)); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))))
global: x0$3134(1)(HSEtyvar(a(7399))), cmp$3135(1)(HSEfun(HSEtyvar(a(7399)), HSEtyvar(a(7399)); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))))
*/
ATSstaticdec()
atstkind_t0ype(atstype_bool)
loop_6__6(atstyvar_type(a) env0, atstype_funptr env1, atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstype_boxed) ;
ATStmpdec(tmpret6, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7, atstyvar_type(a)) ;
ATStmpdec(tmp8, atstype_boxed) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3638(line=153, offs=5) -- 4006(line=172, offs=2)
*/
__patsflab_loop_6:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3702(line=159, offs=3) -- 4004(line=171, offs=33)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3718(line=160, offs=5) -- 3741(line=161, offs=14)
*/
__atstmplab0:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3663(line=156, offs=3) -- 3665(line=156, offs=5)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab3) ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3741(line=161, offs=14) -- 3741(line=161, offs=14)
*/
__atstmplab1:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3735(line=161, offs=8) -- 3736(line=161, offs=9)
*/
ATSINSmove(tmp7, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3738(line=161, offs=11) -- 3740(line=161, offs=13)
*/
ATSINSmove(tmp8, ATSSELcon(arg0, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3745(line=161, offs=18) -- 3949(line=170, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3773(line=163, offs=9) -- 3804(line=163, offs=40)
*/
ATSINSmove(tmp9, PMVtmpltcst(compare_elt_elt<S2Evar(a(7399))>)(env0, tmp7, env1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3843(line=166, offs=10) -- 3850(line=166, offs=17)
*/
ATSINSmove(tmp10, PMVtmpltcst(gt_g0int_int<S2Eextkind(atstype_int)>)(tmp9, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3840(line=166, offs=7) -- 3920(line=168, offs=51)
*/
ATSif(
tmp10
) ATSthen() {
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3864(line=167, offs=14) -- 3869(line=167, offs=19)
*/
ATSINSmove(tmpret6, ATSPMVbool_false()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3887(line=168, offs=18) -- 3894(line=168, offs=25)
*/
ATSINSmove(tmp11, PMVtmpltcst(lt_g0int_int<S2Eextkind(atstype_int)>)(tmp9, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3884(line=168, offs=15) -- 3919(line=168, offs=50)
*/
ATSif(
tmp11
) ATSthen() {
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3900(line=168, offs=31) -- 3908(line=168, offs=39)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp8) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSgoto(__patsflab_loop_6) ;
ATStailcalend()

} ATSelse() {
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3915(line=168, offs=46) -- 3919(line=168, offs=50)
*/
ATSINSmove(tmpret6, ATSPMVbool_true()) ;
} /* ATSendif */
} /* ATSendif */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3745(line=161, offs=18) -- 3949(line=170, offs=8)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3976(line=171, offs=5) -- 3995(line=171, offs=24)
*/
__atstmplab2:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3663(line=156, offs=3) -- 3665(line=156, offs=5)
*/
#if(0)
if (ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3995(line=171, offs=24) -- 3995(line=171, offs=24)
*/
__atstmplab3:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3999(line=171, offs=28) -- 4004(line=171, offs=33)
*/
ATSINSmove(tmpret6, ATSPMVbool_false()) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret6) ;
} /* end of [loop_6__6] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3611(line=151, offs=3) -- 4048(line=176, offs=4)
*/
/*
local: 
global: funset_is_member$5$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(7399)
tmparg = S2Evar(a(7399))
tmpsub = Some(a(7399) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)))
*/
atstkind_t0ype(atstype_bool)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_is_member__5__1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3592(line=150, offs=1) -- 4048(line=176, offs=4)
*/
__patsflab_funset_is_member:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3627(line=151, offs=19) -- 4048(line=176, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 4035(line=175, offs=3) -- 4043(line=175, offs=11)
*/
ATSINSmove(tmpret5__1, loop_6__6__1(arg1, arg2, arg0)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3627(line=151, offs=19) -- 4048(line=176, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret5__1) ;
} /* end of [_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__funset_is_member__5__1] */

/*
/home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3638(line=153, offs=5) -- 4006(line=172, offs=2)
*/
/*
local: loop_6$1(level=2)
global: loop_6$1(level=2)
local: x0$3134(1)(HSEs2exp(S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)))), cmp$3135(1)(HSEfun(HSEs2exp(S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))), HSEs2exp(S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))))
global: x0$3134(1)(HSEs2exp(S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)))), cmp$3135(1)(HSEfun(HSEs2exp(S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))), HSEs2exp(S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))))
*/
ATSstaticdec()
atstkind_t0ype(atstype_bool)
loop_6__6__1(atstkind_t0ype(atstype_int) env0, atstype_funptr env1, atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstype_boxed) ;
ATStmpdec(tmpret6__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp8__1, atstype_boxed) ;
ATStmpdec(tmp9__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp10__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp11__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3638(line=153, offs=5) -- 4006(line=172, offs=2)
*/
__patsflab_loop_6:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3702(line=159, offs=3) -- 4004(line=171, offs=33)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3718(line=160, offs=5) -- 3741(line=161, offs=14)
*/
__atstmplab0:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3663(line=156, offs=3) -- 3665(line=156, offs=5)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab3) ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3741(line=161, offs=14) -- 3741(line=161, offs=14)
*/
__atstmplab1:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3735(line=161, offs=8) -- 3736(line=161, offs=9)
*/
ATSINSmove(tmp7__1, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3738(line=161, offs=11) -- 3740(line=161, offs=13)
*/
ATSINSmove(tmp8__1, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3745(line=161, offs=18) -- 3949(line=170, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3773(line=163, offs=9) -- 3804(line=163, offs=40)
*/
ATSINSmove(tmp9__1, _057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__compare_elt_elt__0__1(env0, tmp7__1, env1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3843(line=166, offs=10) -- 3850(line=166, offs=17)
*/
ATSINSmove(tmp10__1, ATSLIB_056_prelude__gt_g0int_int__11__1(tmp9__1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3840(line=166, offs=7) -- 3920(line=168, offs=51)
*/
ATSif(
tmp10__1
) ATSthen() {
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3864(line=167, offs=14) -- 3869(line=167, offs=19)
*/
ATSINSmove(tmpret6__1, ATSPMVbool_false()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3887(line=168, offs=18) -- 3894(line=168, offs=25)
*/
ATSINSmove(tmp11__1, ATSLIB_056_prelude__lt_g0int_int__15__1(tmp9__1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3884(line=168, offs=15) -- 3919(line=168, offs=50)
*/
ATSif(
tmp11__1
) ATSthen() {
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3900(line=168, offs=31) -- 3908(line=168, offs=39)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp8__1) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSgoto(__patsflab_loop_6) ;
ATStailcalend()

} ATSelse() {
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3915(line=168, offs=46) -- 3919(line=168, offs=50)
*/
ATSINSmove(tmpret6__1, ATSPMVbool_true()) ;
} /* ATSendif */
} /* ATSendif */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3745(line=161, offs=18) -- 3949(line=170, offs=8)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3976(line=171, offs=5) -- 3995(line=171, offs=24)
*/
__atstmplab2:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3663(line=156, offs=3) -- 3665(line=156, offs=5)
*/
#if(0)
if (ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3995(line=171, offs=24) -- 3995(line=171, offs=24)
*/
__atstmplab3:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/libats/ATS1/DATS/funset_listord.dats: 3999(line=171, offs=28) -- 4004(line=171, offs=33)
*/
ATSINSmove(tmpret6__1, ATSPMVbool_false()) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret6__1) ;
} /* end of [loop_6__6__1] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 870(line=58, offs=26) -- 887(line=58, offs=43)
*/
/*
local: 
global: compare_elt_elt$0$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = 
tmparg = S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind))
tmpsub = Some()
*/
atstkind_t0ype(atstype_int)
_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__compare_elt_elt__0__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 845(line=58, offs=1) -- 887(line=58, offs=43)
*/
__patsflab_compare_elt_elt:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 882(line=58, offs=38) -- 887(line=58, offs=43)
*/
ATSINSmove(tmpret0__1, atspre_g0int_sub_int(arg0, arg1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret0__1) ;
} /* end of [_057_home_057_brand_000_057_ATS_055_Postiats_057_libats_057_ATS1_057_SATS_057_funset_listord_056_sats__compare_elt_elt__0__1] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28132(line=758, offs=14) -- 28172(line=758, offs=54)
*/
/*
local: 
global: gt_g0int_int$11$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(4343)
tmparg = S2Evar(tk(4343))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__11(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28119(line=758, offs=1) -- 28172(line=758, offs=54)
*/
__patsflab_gt_g0int_int:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28158(line=758, offs=40) -- 28170(line=758, offs=52)
*/
ATSINSmove(tmp21, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4343))>)(arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28141(line=758, offs=23) -- 28172(line=758, offs=54)
*/
ATSINSmove(tmpret20, PMVtmpltcst(g0int_gt<S2Evar(tk(4343))>)(arg0, tmp21)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret20) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__11] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28132(line=758, offs=14) -- 28172(line=758, offs=54)
*/
/*
local: 
global: gt_g0int_int$11$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(4343)
tmparg = S2Evar(tk(4343))
tmpsub = Some(tk(4343) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__11__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28119(line=758, offs=1) -- 28172(line=758, offs=54)
*/
__patsflab_gt_g0int_int:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28158(line=758, offs=40) -- 28170(line=758, offs=52)
*/
ATSINSmove(tmp21__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28141(line=758, offs=23) -- 28172(line=758, offs=54)
*/
ATSINSmove(tmpret20__1, atspre_g0int_gt_int(arg0, tmp21__1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret20__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__11__1] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 27994(line=754, offs=14) -- 28034(line=754, offs=54)
*/
/*
local: 
global: lt_g0int_int$15$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(4341)
tmparg = S2Evar(tk(4341))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__15(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 27981(line=754, offs=1) -- 28034(line=754, offs=54)
*/
__patsflab_lt_g0int_int:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28020(line=754, offs=40) -- 28032(line=754, offs=52)
*/
ATSINSmove(tmp25, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4341))>)(arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28003(line=754, offs=23) -- 28034(line=754, offs=54)
*/
ATSINSmove(tmpret24, PMVtmpltcst(g0int_lt<S2Evar(tk(4341))>)(arg0, tmp25)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret24) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__15] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 27994(line=754, offs=14) -- 28034(line=754, offs=54)
*/
/*
local: 
global: lt_g0int_int$15$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(4341)
tmparg = S2Evar(tk(4341))
tmpsub = Some(tk(4341) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__15__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp25__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 27981(line=754, offs=1) -- 28034(line=754, offs=54)
*/
__patsflab_lt_g0int_int:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28020(line=754, offs=40) -- 28032(line=754, offs=52)
*/
ATSINSmove(tmp25__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28003(line=754, offs=23) -- 28034(line=754, offs=54)
*/
ATSINSmove(tmpret24__1, atspre_g0int_lt_int(arg0, tmp25__1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret24__1) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__15__1] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1099(line=72, offs=3) -- 1963(line=109, offs=4)
*/
/*
local: 
global: grexplst_cnfize_ifnot$18$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_boxed
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__grexplst_cnfize_ifnot(atstype_boxed arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret28, atstype_boxed) ;
ATStmpdec(tmp48, atstype_boxed) ;
ATStmpdec(tmp49, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1075(line=71, offs=1) -- 1963(line=109, offs=4)
*/
__patsflab_grexplst_cnfize_ifnot:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1116(line=72, offs=20) -- 1963(line=109, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1917(line=105, offs=25) -- 1928(line=105, offs=36)
*/

ATSINSmove_con0(tmp49, 0) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1903(line=105, offs=11) -- 1929(line=105, offs=37)
*/
ATSINSmove(tmp48, loop_19(arg1, arg0, ATSPMVi0nt(1), tmp49)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1938(line=108, offs=3) -- 1958(line=108, offs=23)
*/
ATSINSmove(tmpret28, ATSLIB_056_prelude__list_vt_reverse__21__1(tmp48)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1116(line=72, offs=20) -- 1963(line=109, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret28) ;
} /* end of [_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__grexplst_cnfize_ifnot] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1127(line=74, offs=5) -- 1872(line=103, offs=4)
*/
/*
local: loop_19$0(level=1)
global: loop_19$0(level=1)
local: skipped$3674(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: skipped$3674(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstype_boxed
loop_19(atstkind_type(atstype_ptrk) env0, atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1, atstype_boxed arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstype_boxed) ;
ATStmpdec(argx1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(argx2, atstype_boxed) ;
ATStmpdec(tmpret29, atstype_boxed) ;
ATStmpdec(tmp30, atstype_boxed) ;
ATStmpdec(tmp31, atstype_boxed) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp33, atsvoid_t0ype) ;
ATStmpdec_void(tmp34, atsvoid_t0ype) ;
ATStmpdec_void(tmp35, atsvoid_t0ype) ;
ATStmpdec_void(tmp36, atsvoid_t0ype) ;
ATStmpdec_void(tmp37, atsvoid_t0ype) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp39, atsvoid_t0ype) ;
ATStmpdec_void(tmp40, atsvoid_t0ype) ;
ATStmpdec_void(tmp41, atsvoid_t0ype) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp43, atstkind_type(atstype_ptrk)) ;
ATStmpdec_void(tmp44, atsvoid_t0ype) ;
ATStmpdec_void(tmp45, atsvoid_t0ype) ;
ATStmpdec(tmp46, atstype_boxed) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1127(line=74, offs=5) -- 1872(line=103, offs=4)
*/
__patsflab_loop_19:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1201(line=80, offs=1) -- 1843(line=101, offs=6)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1216(line=81, offs=3) -- 1227(line=81, offs=14)
*/
__atstmplab4:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1136(line=76, offs=3) -- 1139(line=76, offs=6)
*/
if (ATSCKptriscons(arg0)) { ATSgoto(__atstmplab7) ; }
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1227(line=81, offs=14) -- 1227(line=81, offs=14)
*/
__atstmplab5:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1231(line=81, offs=18) -- 1234(line=81, offs=21)
*/
ATSINSmove(tmpret29, arg2) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1237(line=82, offs=3) -- 1260(line=83, offs=14)
*/
__atstmplab6:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1136(line=76, offs=3) -- 1139(line=76, offs=6)
*/
#if(0)
if (ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1260(line=83, offs=14) -- 1260(line=83, offs=14)
*/
__atstmplab7:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1252(line=83, offs=6) -- 1254(line=83, offs=8)
*/
ATSINSmove(tmp30, ATSSELcon(arg0, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1256(line=83, offs=10) -- 1259(line=83, offs=13)
*/
ATSINSmove(tmp31, ATSSELcon(arg0, postiats_tysum_2, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1264(line=83, offs=18) -- 1843(line=101, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1283(line=84, offs=16) -- 1316(line=84, offs=49)
*/
ATSINSmove(tmp32, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__ruleset_is_member(env0, arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1330(line=85, offs=14) -- 1394(line=85, offs=78)
*/
ATSif(
tmp32
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1343(line=85, offs=27) -- 1394(line=85, offs=78)
*/
ATSINSmove_void(tmp34, atspre_fprint_string(atspre_FILE_stderr, ATSPMVstring("Skipping rule("))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1343(line=85, offs=27) -- 1394(line=85, offs=78)
*/
ATSINSmove_void(tmp35, atspre_fprint_int(atspre_FILE_stderr, arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1343(line=85, offs=27) -- 1394(line=85, offs=78)
*/
ATSINSmove_void(tmp36, atspre_fprint_string(atspre_FILE_stderr, ATSPMVstring(")"))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1343(line=85, offs=27) -- 1394(line=85, offs=78)
*/
ATSINSmove_void(tmp33, atspre_fprint_newline(atspre_FILE_stderr)) ;

} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1394(line=85, offs=78) -- 1394(line=85, offs=78)
*/
ATSINSmove_void(tmp33, ATSempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1412(line=86, offs=17) -- 1417(line=86, offs=22)
*/
ATSINSmove(tmp38, atspre_neg_bool0(tmp32)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1409(line=86, offs=14) -- 1476(line=86, offs=81)
*/
ATSif(
tmp38
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1423(line=86, offs=28) -- 1476(line=86, offs=81)
*/
ATSINSmove_void(tmp39, atspre_fprint_string(atspre_FILE_stderr, ATSPMVstring("Processing rule("))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1423(line=86, offs=28) -- 1476(line=86, offs=81)
*/
ATSINSmove_void(tmp40, atspre_fprint_int(atspre_FILE_stderr, arg1)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1423(line=86, offs=28) -- 1476(line=86, offs=81)
*/
ATSINSmove_void(tmp41, atspre_fprint_string(atspre_FILE_stderr, ATSPMVstring(")"))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1423(line=86, offs=28) -- 1476(line=86, offs=81)
*/
ATSINSmove_void(tmp37, atspre_fprint_newline(atspre_FILE_stderr)) ;

} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1476(line=86, offs=81) -- 1476(line=86, offs=81)
*/
ATSINSmove_void(tmp37, ATSempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1487(line=88, offs=5) -- 1799(line=99, offs=10)
*/
ATSif(
tmp32
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1525(line=90, offs=20) -- 1531(line=90, offs=26)
*/
ATSINSmove(tmp42, atspre_g0int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1514(line=90, offs=9) -- 1537(line=90, offs=32)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp31) ;
ATSINSmove_tlcal(argx1, tmp42) ;
ATSINSmove_tlcal(argx2, arg2) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSINSargmove_tlcal(arg2, argx2) ;
ATSgoto(__patsflab_loop_19) ;
ATStailcalend()

} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1549(line=91, offs=12) -- 1799(line=99, offs=10)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1571(line=92, offs=19) -- 1587(line=92, offs=35)
*/
ATSINSmove(tmp43, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grexp_cnfize(tmp30)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1618(line=94, offs=11) -- 1648(line=94, offs=41)
*/
ATSINSmove_void(tmp44, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__fprint_grcnf(atspre_FILE_stderr, ATSPMVrefarg0(tmp43))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1650(line=94, offs=43) -- 1676(line=94, offs=69)
*/
ATSINSmove_void(tmp45, atspre_fprint_newline(atspre_FILE_stderr)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1725(line=96, offs=19) -- 1748(line=96, offs=42)
*/

ATSINSmove_con1(tmp46, postiats_tysum_2) ;
#if(0)
ATSINSstore_con_tag(tmp46, 0) ;
#endif
ATSINSstore_con_ofs(tmp46, postiats_tysum_2, atslab__0, tmp43) ;
ATSINSstore_con_ofs(tmp46, postiats_tysum_2, atslab__1, arg2) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1777(line=98, offs=20) -- 1783(line=98, offs=26)
*/
ATSINSmove(tmp47, atspre_g0int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1766(line=98, offs=9) -- 1789(line=98, offs=32)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp31) ;
ATSINSmove_tlcal(argx1, tmp47) ;
ATSINSmove_tlcal(argx2, tmp46) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSINSargmove_tlcal(arg2, argx2) ;
ATSgoto(__patsflab_loop_19) ;
ATStailcalend()

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1549(line=91, offs=12) -- 1799(line=99, offs=10)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_cnfize_ifnot.dats: 1264(line=83, offs=18) -- 1843(line=101, offs=6)
*/
/*
INSletpop()
*/
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret29) ;
} /* end of [loop_19] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10018(line=526, offs=17) -- 10068(line=526, offs=67)
*/
/*
local: 
global: list_vt_reverse$21$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(5754)
tmparg = S2Evar(a(5754))
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_prelude__list_vt_reverse__21(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret50, atstype_boxed) ;
ATStmpdec(tmp51, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10002(line=526, offs=1) -- 10068(line=526, offs=67)
*/
__patsflab_list_vt_reverse:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10056(line=526, offs=55) -- 10067(line=526, offs=66)
*/

ATSINSmove_con0(tmp51, 0) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10025(line=526, offs=24) -- 10068(line=526, offs=67)
*/
ATSINSmove(tmpret50, PMVtmpltcst(list_vt_reverse_append<S2Evar(a(5754))>)(arg0, tmp51)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret50) ;
} /* end of [ATSLIB_056_prelude__list_vt_reverse__21] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10018(line=526, offs=17) -- 10068(line=526, offs=67)
*/
/*
local: 
global: list_vt_reverse$21$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(5754)
tmparg = S2Evar(a(5754))
tmpsub = Some(a(5754) -> S2Ecst(grcnf_vtype))
*/
atstype_boxed
ATSLIB_056_prelude__list_vt_reverse__21__1(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret50__1, atstype_boxed) ;
ATStmpdec(tmp51__1, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10002(line=526, offs=1) -- 10068(line=526, offs=67)
*/
__patsflab_list_vt_reverse:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10056(line=526, offs=55) -- 10067(line=526, offs=66)
*/

ATSINSmove_con0(tmp51__1, 0) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10025(line=526, offs=24) -- 10068(line=526, offs=67)
*/
ATSINSmove(tmpret50__1, ATSLIB_056_prelude__list_vt_reverse_append__23__1(arg0, tmp51__1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret50__1) ;
} /* end of [ATSLIB_056_prelude__list_vt_reverse__21__1] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10129(line=532, offs=3) -- 10568(line=555, offs=4)
*/
/*
local: 
global: list_vt_reverse_append$23$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(5756)
tmparg = S2Evar(a(5756))
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_prelude__list_vt_reverse_append__23(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret54, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10104(line=531, offs=1) -- 10568(line=555, offs=4)
*/
__patsflab_list_vt_reverse_append:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10140(line=532, offs=14) -- 10568(line=555, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10551(line=554, offs=3) -- 10564(line=554, offs=16)
*/
ATSINSmove(tmpret54, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$1518(1), flab=loop_24$0(level=1)), (atstype_boxed, atstype_boxed), atstype_boxed)(arg0, arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10140(line=532, offs=14) -- 10568(line=555, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret54) ;
} /* end of [ATSLIB_056_prelude__list_vt_reverse_append__23] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10226(line=537, offs=5) -- 10522(line=550, offs=26)
*/
/*
local: loop_24$0(level=1)
global: loop_24$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
loop_24__24(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstype_boxed) ;
ATStmpdec(argx1, atstype_boxed) ;
ATStmpdec(tmpret55, atstype_boxed) ;
ATStmpdec(tmp58, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10226(line=537, offs=5) -- 10522(line=550, offs=26)
*/
__patsflab_loop_24:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10323(line=542, offs=3) -- 10522(line=550, offs=26)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10338(line=543, offs=5) -- 10366(line=544, offs=15)
*/
__atstmplab8:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10253(line=540, offs=3) -- 10255(line=540, offs=5)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab11) ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10366(line=544, offs=15) -- 10366(line=544, offs=15)
*/
__atstmplab9:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10370(line=544, offs=19) -- 10479(line=549, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10391(line=545, offs=18) -- 10394(line=545, offs=21)
*/
ATSINSmove(tmp58, ATSSELcon(arg0, postiats_tysum_3, atslab__1)) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10410(line=546, offs=16) -- 10419(line=546, offs=25)
*/
ATSINSstore(ATSSELcon(arg0, postiats_tysum_3, atslab__1), arg1) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10456(line=548, offs=7) -- 10471(line=548, offs=22)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp58) ;
ATSINSmove_tlcal(argx1, arg0) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSgoto(__patsflab_loop_24) ;
ATStailcalend()

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10370(line=544, offs=19) -- 10479(line=549, offs=8)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10501(line=550, offs=5) -- 10516(line=550, offs=20)
*/
__atstmplab10:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10253(line=540, offs=3) -- 10255(line=540, offs=5)
*/
if (ATSCKptriscons(arg0)) { ATSINScaseof_fail("/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10323(line=542, offs=3) -- 10522(line=550, offs=26)") ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10516(line=550, offs=20) -- 10516(line=550, offs=20)
*/
__atstmplab11:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10520(line=550, offs=24) -- 10522(line=550, offs=26)
*/
ATSINSmove(tmpret55, arg1) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret55) ;
} /* end of [loop_24__24] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10129(line=532, offs=3) -- 10568(line=555, offs=4)
*/
/*
local: 
global: list_vt_reverse_append$23$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(5756)
tmparg = S2Evar(a(5756))
tmpsub = Some(a(5756) -> S2Ecst(grcnf_vtype))
*/
atstype_boxed
ATSLIB_056_prelude__list_vt_reverse_append__23__1(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret54__1, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10104(line=531, offs=1) -- 10568(line=555, offs=4)
*/
__patsflab_list_vt_reverse_append:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10140(line=532, offs=14) -- 10568(line=555, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10551(line=554, offs=3) -- 10564(line=554, offs=16)
*/
ATSINSmove(tmpret54__1, loop_24__24__1(arg0, arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10140(line=532, offs=14) -- 10568(line=555, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret54__1) ;
} /* end of [ATSLIB_056_prelude__list_vt_reverse_append__23__1] */

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10226(line=537, offs=5) -- 10522(line=550, offs=26)
*/
/*
local: loop_24$1(level=3)
global: loop_24$1(level=3)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
loop_24__24__1(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstype_boxed) ;
ATStmpdec(argx1, atstype_boxed) ;
ATStmpdec(tmpret55__1, atstype_boxed) ;
ATStmpdec(tmp58__1, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10226(line=537, offs=5) -- 10522(line=550, offs=26)
*/
__patsflab_loop_24:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10323(line=542, offs=3) -- 10522(line=550, offs=26)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10338(line=543, offs=5) -- 10366(line=544, offs=15)
*/
__atstmplab8:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10253(line=540, offs=3) -- 10255(line=540, offs=5)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab11) ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10366(line=544, offs=15) -- 10366(line=544, offs=15)
*/
__atstmplab9:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10370(line=544, offs=19) -- 10479(line=549, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10391(line=545, offs=18) -- 10394(line=545, offs=21)
*/
ATSINSmove(tmp58__1, ATSSELcon(arg0, postiats_tysum_4, atslab__1)) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10410(line=546, offs=16) -- 10419(line=546, offs=25)
*/
ATSINSstore(ATSSELcon(arg0, postiats_tysum_4, atslab__1), arg1) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10456(line=548, offs=7) -- 10471(line=548, offs=22)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp58__1) ;
ATSINSmove_tlcal(argx1, arg0) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSgoto(__patsflab_loop_24) ;
ATStailcalend()

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10370(line=544, offs=19) -- 10479(line=549, offs=8)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10501(line=550, offs=5) -- 10516(line=550, offs=20)
*/
__atstmplab10:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10253(line=540, offs=3) -- 10255(line=540, offs=5)
*/
if (ATSCKptriscons(arg0)) { ATSINScaseof_fail("/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10323(line=542, offs=3) -- 10522(line=550, offs=26)") ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10516(line=550, offs=20) -- 10516(line=550, offs=20)
*/
__atstmplab11:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 10520(line=550, offs=24) -- 10522(line=550, offs=26)
*/
ATSINSmove(tmpret55__1, arg1) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret55__1) ;
} /* end of [loop_24__24__1] */

/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__dynload()
{
ATSdynload1(
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_cnfize_ifnot_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* in of [local] */
/* (*nothing*) */
/* end of [local] */
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
