/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-4-17: 16h:22m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 1839(line=58, offs=1) -- 1879(line=58, offs=41)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/string.sats: 1380(line=35, offs=1) -- 1419(line=37, offs=3)
*/

#include "libc/CATS/string.cats"
/*
/home/brand_000/ATS-Postiats/prelude/DATS/filebas.dats: 13966(line=737, offs=1) -- 13996(line=737, offs=31)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/brand_000/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/brand_000/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/stream.dats: 1564(line=46, offs=1) -- 1603(line=46, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/stream_vt.dats: 1567(line=46, offs=1) -- 1606(line=46, offs=40)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/brand_000/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/math.sats: 1380(line=35, offs=1) -- 1417(line=37, offs=3)
*/

#include "libc/CATS/math.cats"
/*
/home/brand_000/ATS-Postiats/libc/DATS/math.dats: 1566(line=41, offs=1) -- 1595(line=41, offs=30)
*/
/*
/home/brand_000/ATS-Postiats/libc/SATS/math.sats: 1380(line=35, offs=1) -- 1417(line=37, offs=3)
*/

#include "libc/CATS/math.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
atstkind_t0ype(atstype_double) atslab__0; 
atstkind_t0ype(atstype_double) atslab__1; 
} postiats_tyrec_0 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_1 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_2 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_3 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(b) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_4 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(b) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_5 ;
typedef
struct {
#if(0)
int contag ;
#endif
postiats_tyrec_0 atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_6 ;
typedef
struct {
#if(0)
int contag ;
#endif
postiats_tyrec_0 atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_7 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__GDMap_find, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_t0ype(atstype_double))), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atslib_isnan_double)
ATSdyncst_mac(atspre_g0float_add_double)
ATSdyncst_mac(atspre_g0float_mul_double)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__genes_listize1, (atsrefarg0_type(atstkind_type(atstype_ptrk))), atstype_boxed) ;
ATSdyncst_mac(atspre_g1int_add_int)
ATSdyncst_mac(atspre_g0int_sub_int)
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_make, (atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)), postiats_tyrec_0) ;
ATSdyncst_mac(atspre_mul_int_double)
ATSdyncst_mac(atspre_div_double_int)
ATSdyncst_mac(atspre_g0float_div_double)
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grcnf_minmean_stdev, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)), postiats_tyrec_0) ;
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__genes_meanvar, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)), postiats_tyrec_0) ;
ATSdyncst_mac(atspre_g0float_lt_double)
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_get_exp, (postiats_tyrec_0), atstkind_t0ype(atstype_double)) ;
ATSdyncst_extfun(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_get_var, (postiats_tyrec_0), atstkind_t0ype(atstype_double)) ;
ATSdyncst_mac(atspre_g0float_eq_double)
ATSdyncst_mac(atslib_sqrt_double)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSglobaldec()
postiats_tyrec_0
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__genes_meanvar(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstkind_t0ype(atstype_int)
loop_1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstype_boxed, atstkind_t0ype(atstype_int), atsrefarg1_type(atstkind_t0ype(atstype_double)), atsrefarg1_type(atstkind_t0ype(atstype_double))) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__list_vt_length__10(atsrefarg0_type(atstype_boxed)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstkind_t0ype(atstype_int)
loop_11__11(atsrefarg0_type(atstype_boxed), atstkind_t0ype(atstype_int)) ;
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__list_vt_length__10__1(atsrefarg0_type(atstype_boxed)) ;

ATSstaticdec()
atstkind_t0ype(atstype_int)
loop_11__11__1(atsrefarg0_type(atstype_boxed), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__16(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__16__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atstype_boxed
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grcnflst_minmean_stdev(atsrefarg0_type(atstype_boxed), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSglobaldec()
atstype_boxed
ATSLIB_056_prelude__list_vt_map_cloref__21(atsrefarg0_type(atstype_boxed), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstyvar_type(y2)
ATSLIB_056_prelude__list_vt_map__fopr__22(atstype_funptr, atsrefarg1_type(atstyvar_type(x2))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstype_boxed
ATSLIB_056_prelude__list_vt_map_cloref__21__1(atsrefarg0_type(atstype_boxed), atstype_cloptr) ;

#if(0)
#if(0)
ATSglobaldec()
atstype_boxed
ATSLIB_056_prelude__list_vt_map__24(atsrefarg0_type(atstype_boxed)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atsvoid_t0ype
loop_25__25(atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [TEMPLATE]

ATSstaticdec()
atstype_boxed
ATSLIB_056_prelude__list_vt_map__24__1(atstype_funptr, atsrefarg0_type(atstype_boxed)) ;

ATSstaticdec()
atsvoid_t0ype
loop_25__25__1(atstype_funptr, atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

ATSstaticdec()
postiats_tyrec_0
ATSLIB_056_prelude__list_vt_map__fopr__22__1(atstype_funptr, atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

ATSstaticdec()
postiats_tyrec_0
__patsfun_29(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

#if(0)
ATSglobaldec()
postiats_tyrec_0
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grcnf_minmean_stdev(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atsvoid_t0ype
loop_31(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstkind_t0ype(atstype_double)), atsrefarg1_type(atstkind_t0ype(atstype_double))) ;

typedef struct
{
atstype_funptr cfun ;
atstkind_type(atstype_ptrk) env0 ;
atstkind_type(atstype_ptrk) env1 ;
} __patsfun_29__closure_t0ype ;
ATSstaticdec()
postiats_tyrec_0
__patsfun_29__cfun
(
__patsfun_29__closure_t0ype *p_cenv, atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0
)
{
ATSFCreturn(__patsfun_29(p_cenv->env0, p_cenv->env1, arg0)) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_29__closureinit
(
__patsfun_29__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_29__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_29__closurerize
(
atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) env1
)
{
return __patsfun_29__closureinit(ATS_MALLOC(sizeof(__patsfun_29__closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1707(line=100, offs=3) -- 3248(line=169, offs=4)
*/
/*
local: 
global: genes_meanvar$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
postiats_tyrec_0
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__genes_meanvar(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_type(atstype_ptrk) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, postiats_tyrec_0) ;
ATStmpdec(tmpref22, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmpref23, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp24, atstype_boxed) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp37, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp43, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1691(line=99, offs=1) -- 3248(line=169, offs=4)
*/
__patsflab_genes_meanvar:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1726(line=100, offs=22) -- 3248(line=169, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2968(line=156, offs=5) -- 2972(line=156, offs=9)
*/
/*
ATSINStmpdec(tmpref22) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2983(line=156, offs=20) -- 2986(line=156, offs=23)
*/
ATSINSmove(tmpref22, ATSPMVf0loat(0.0)) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2991(line=157, offs=5) -- 2995(line=157, offs=9)
*/
/*
ATSINStmpdec(tmpref23) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3006(line=157, offs=20) -- 3009(line=157, offs=23)
*/
ATSINSmove(tmpref23, ATSPMVf0loat(0.0)) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3022(line=159, offs=10) -- 3040(line=159, offs=28)
*/
ATSINSmove(tmp24, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__genes_listize1(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3052(line=160, offs=11) -- 3070(line=160, offs=29)
*/
ATSINSmove(tmp25, ATSLIB_056_prelude__list_vt_length__10__1(ATSPMVrefarg0(tmp24))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3083(line=161, offs=12) -- 3115(line=161, offs=44)
*/
ATSINSmove(tmp35, loop_1(arg1, arg2, tmp24, ATSPMVi0nt(0), ATSPMVrefarg1(ATSPMVptrof(tmpref22)), ATSPMVrefarg1(ATSPMVptrof(tmpref23)))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3127(line=162, offs=12) -- 3137(line=162, offs=22)
*/
ATSINSmove(tmp36, atspre_g0int_sub_int(tmp25, tmp35)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3150(line=166, offs=4) -- 3158(line=166, offs=12)
*/
ATSINSmove(tmp37, ATSLIB_056_prelude__gt_g0int_int__16__1(tmp36, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3147(line=166, offs=1) -- 3229(line=167, offs=71)
*/
ATSif(
tmp37
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3184(line=167, offs=26) -- 3193(line=167, offs=35)
*/
ATSINSmove(tmp43, atspre_div_double_int(tmpref22, tmp36)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3179(line=167, offs=21) -- 3193(line=167, offs=35)
*/
ATSINSmove(tmp42, atspre_mul_int_double(tmp25, tmp43)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3166(line=167, offs=8) -- 3201(line=167, offs=43)
*/
ATSINSmove(tmpret0, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_make(tmp42, tmpref23)) ;

} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3220(line=167, offs=62) -- 3223(line=167, offs=65)
*/
ATSINSmove(tmp44, atspre_g0float_div_double(ATSPMVf0loat(0.0), ATSPMVf0loat(0.0))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3225(line=167, offs=67) -- 3228(line=167, offs=70)
*/
ATSINSmove(tmp45, atspre_g0float_div_double(ATSPMVf0loat(0.0), ATSPMVf0loat(0.0))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3207(line=167, offs=49) -- 3229(line=167, offs=71)
*/
ATSINSmove(tmpret0, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_make(tmp44, tmp45)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1726(line=100, offs=22) -- 3248(line=169, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__genes_meanvar] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1737(line=102, offs=5) -- 2960(line=154, offs=2)
*/
/*
local: loop_1$0(level=1)
global: loop_1$0(level=1)
local: emap$3106(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), smap$3107(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: emap$3106(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), smap$3107(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
loop_1(atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) env1, atstype_boxed arg0, atstkind_t0ype(atstype_int) arg1, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg2, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstype_boxed) ;
ATStmpdec(argx1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(argx2, atsrefarg1_type(atstkind_t0ype(atstype_double))) ;
ATStmpdec(argx3, atsrefarg1_type(atstkind_t0ype(atstype_double))) ;
ATStmpdec(tmpret1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3, atstype_boxed) ;
ATStmpdec(tmpref4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmpref5, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp7, atsvoid_t0ype) ;
ATStmpdec_void(tmp8, atsvoid_t0ype) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_double)) ;
ATStmpdec_void(tmp16, atsvoid_t0ype) ;
ATStmpdec(tmpref17, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1737(line=102, offs=5) -- 2960(line=154, offs=2)
*/
__patsflab_loop_1:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1833(line=108, offs=1) -- 2933(line=153, offs=6)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1847(line=109, offs=3) -- 1862(line=109, offs=18)
*/
__atstmplab0:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1746(line=104, offs=3) -- 1748(line=104, offs=5)
*/
if (ATSCKptriscons(arg0)) { ATSgoto(__atstmplab3) ; }
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1862(line=109, offs=18) -- 1862(line=109, offs=18)
*/
__atstmplab1:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1866(line=109, offs=22) -- 1870(line=109, offs=26)
*/
ATSINSmove(tmpret1, arg1) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1873(line=110, offs=3) -- 1894(line=110, offs=24)
*/
__atstmplab2:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1746(line=104, offs=3) -- 1748(line=104, offs=5)
*/
#if(0)
if (ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1894(line=110, offs=24) -- 1894(line=110, offs=24)
*/
__atstmplab3:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1888(line=110, offs=18) -- 1889(line=110, offs=19)
*/
ATSINSmove(tmp2, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1891(line=110, offs=21) -- 1893(line=110, offs=23)
*/
ATSINSmove(tmp3, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1873(line=110, offs=3) -- 2933(line=153, offs=6)
*/
ATSINSfreecon(arg0) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1898(line=110, offs=28) -- 2933(line=153, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1913(line=112, offs=9) -- 1917(line=112, offs=13)
*/
/*
ATSINStmpdec(tmpref4) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1926(line=112, offs=22) -- 1931(line=112, offs=27)
*/
ATSINSmove(tmpref4, ATSPMVbool_false()) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1943(line=114, offs=9) -- 1947(line=114, offs=13)
*/
/*
ATSINStmpdec(tmpref5) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1972(line=115, offs=16) -- 1998(line=115, offs=42)
*/
ATSINSmove(tmp6, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__GDMap_find(env0, tmp2, ATSPMVrefarg1(ATSPMVptrof(tmpref5)))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2018(line=117, offs=5) -- 2330(line=128, offs=10)
*/
ATSif(
tmp6
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2037(line=118, offs=12) -- 2236(line=125, offs=10)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2116(line=121, offs=14) -- 2129(line=121, offs=27)
*/
ATSINSmove(tmp14, atslib_isnan_double(tmpref5)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2116(line=121, offs=14) -- 2134(line=121, offs=32)
*/
ATSINSmove(tmp9, ATSLIB_056_prelude__eq_g0int_int__2__1(tmp14, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2113(line=121, offs=11) -- 2152(line=121, offs=50)
*/
ATSif(
tmp9
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2140(line=121, offs=38) -- 2152(line=121, offs=50)
*/
ATSINSstore(tmpref4, ATSPMVbool_true()) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2140(line=121, offs=38) -- 2152(line=121, offs=50)
*/
ATSINSmove_void(tmp8, ATSempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2152(line=121, offs=50) -- 2152(line=121, offs=50)
*/
ATSINSmove_void(tmp8, ATSempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2194(line=124, offs=9) -- 2226(line=124, offs=41)
*/
ATSif(
tmpref4
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2215(line=124, offs=30) -- 2226(line=124, offs=41)
*/
ATSINSmove(tmp15, atspre_g0float_add_double(ATSderef(arg2, atstkind_t0ype(atstype_double)), tmpref5)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2207(line=124, offs=22) -- 2226(line=124, offs=41)
*/
ATSINSstore(ATSderef(arg2, atstkind_t0ype(atstype_double)), tmp15) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2207(line=124, offs=22) -- 2226(line=124, offs=41)
*/
ATSINSmove_void(tmp7, ATSempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2226(line=124, offs=41) -- 2226(line=124, offs=41)
*/
ATSINSmove_void(tmp7, ATSempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2037(line=118, offs=12) -- 2236(line=125, offs=10)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2306(line=127, offs=38) -- 2330(line=128, offs=10)
*/
ATSINSmove_void(tmp7, ATSempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2412(line=132, offs=5) -- 2777(line=146, offs=8)
*/
ATSif(
tmpref4
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2425(line=132, offs=18) -- 2777(line=146, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2439(line=133, offs=11) -- 2443(line=133, offs=15)
*/
/*
ATSINStmpdec(tmpref17) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2470(line=134, offs=18) -- 2496(line=134, offs=44)
*/
ATSINSmove(tmp18, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__GDMap_find(env1, tmp2, ATSPMVrefarg1(ATSPMVptrof(tmpref17)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2510(line=136, offs=7) -- 2731(line=144, offs=12)
*/
ATSif(
tmp18
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2610(line=140, offs=26) -- 2619(line=140, offs=35)
*/
ATSINSmove(tmp20, atspre_g0float_mul_double(tmpref17, tmpref17)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2603(line=140, offs=19) -- 2619(line=140, offs=35)
*/
ATSINSmove(tmp19, atspre_g0float_add_double(ATSderef(arg3, atstkind_t0ype(atstype_double)), tmp20)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2595(line=140, offs=11) -- 2619(line=140, offs=35)
*/
ATSINSstore(ATSderef(arg3, atstkind_t0ype(atstype_double)), tmp19) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2595(line=140, offs=11) -- 2619(line=140, offs=35)
*/
ATSINSmove_void(tmp16, ATSempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2705(line=143, offs=40) -- 2731(line=144, offs=12)
*/
ATSINSmove_void(tmp16, ATSempty()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2425(line=132, offs=18) -- 2777(line=146, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2777(line=146, offs=8) -- 2777(line=146, offs=8)
*/
ATSINSmove_void(tmp16, ATSempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2821(line=149, offs=5) -- 2908(line=151, offs=41)
*/
ATSif(
tmpref4
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2840(line=150, offs=12) -- 2867(line=150, offs=39)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp3) ;
ATSINSmove_tlcal(argx1, arg1) ;
ATSINSmove_tlcal(argx2, ATSPMVrefarg1(arg2)) ;
ATSINSmove_tlcal(argx3, ATSPMVrefarg1(arg3)) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSINSargmove_tlcal(arg2, argx2) ;
ATSINSargmove_tlcal(arg3, argx3) ;
ATSgoto(__patsflab_loop_1) ;
ATStailcalend()

} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2889(line=151, offs=22) -- 2895(line=151, offs=28)
*/
ATSINSmove(tmp21, atspre_g0int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 2879(line=151, offs=12) -- 2908(line=151, offs=41)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp3) ;
ATSINSmove_tlcal(argx1, tmp21) ;
ATSINSmove_tlcal(argx2, ATSPMVrefarg1(arg2)) ;
ATSINSmove_tlcal(argx3, ATSPMVrefarg1(arg3)) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSINSargmove_tlcal(arg2, argx2) ;
ATSINSargmove_tlcal(arg3, argx3) ;
ATSgoto(__patsflab_loop_1) ;
ATStailcalend()

} /* ATSendif */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 1898(line=110, offs=28) -- 2933(line=153, offs=6)
*/
/*
INSletpop()
*/
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret1) ;
} /* end of [loop_1] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28270(line=762, offs=14) -- 28310(line=762, offs=54)
*/
/*
local: 
global: eq_g0int_int$2$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(4345)
tmparg = S2Evar(tk(4345))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28257(line=762, offs=1) -- 28310(line=762, offs=54)
*/
__patsflab_eq_g0int_int:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28296(line=762, offs=40) -- 28308(line=762, offs=52)
*/
ATSINSmove(tmp11, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4345))>)(arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28279(line=762, offs=23) -- 28310(line=762, offs=54)
*/
ATSINSmove(tmpret10, PMVtmpltcst(g0int_eq<S2Evar(tk(4345))>)(arg0, tmp11)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret10) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28270(line=762, offs=14) -- 28310(line=762, offs=54)
*/
/*
local: 
global: eq_g0int_int$2$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(4345)
tmparg = S2Evar(tk(4345))
tmpsub = Some(tk(4345) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp11__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28257(line=762, offs=1) -- 28310(line=762, offs=54)
*/
__patsflab_eq_g0int_int:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28296(line=762, offs=40) -- 28308(line=762, offs=52)
*/
ATSINSmove(tmp11__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28279(line=762, offs=23) -- 28310(line=762, offs=54)
*/
ATSINSmove(tmpret10__1, atspre_g0int_eq_int(arg0, tmp11__1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret10__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2__1] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3384(line=136, offs=16) -- 3655(line=156, offs=4)
*/
/*
local: 
global: list_vt_length$10$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(5646)
tmparg = S2Evar(a(5646))
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__list_vt_length__10(atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3369(line=136, offs=1) -- 3655(line=156, offs=4)
*/
__patsflab_list_vt_length:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3391(line=136, offs=23) -- 3655(line=156, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3639(line=155, offs=3) -- 3651(line=155, offs=15)
*/
ATSINSmove(tmpret26, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$1421(1), flab=loop_11$0(level=1)), (atsrefarg0_type(atstype_boxed), atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int))(ATSPMVrefarg0(arg0), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3391(line=136, offs=23) -- 3655(line=156, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret26) ;
} /* end of [ATSLIB_056_prelude__list_vt_length__10] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3402(line=138, offs=5) -- 3574(line=150, offs=4)
*/
/*
local: loop_11$0(level=1)
global: loop_11$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
loop_11__11(atsrefarg0_type(atstype_boxed) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atsrefarg0_type(atstype_boxed)) ;
ATStmpdec(argx1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret27, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp29, atstype_boxed) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3402(line=138, offs=5) -- 3574(line=150, offs=4)
*/
__patsflab_loop_11:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3487(line=145, offs=1) -- 3567(line=148, offs=22)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3501(line=146, offs=3) -- 3525(line=147, offs=12)
*/
__atstmplab4:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3429(line=141, offs=3) -- 3431(line=141, offs=5)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab7) ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3525(line=147, offs=12) -- 3525(line=147, offs=12)
*/
__atstmplab5:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3522(line=147, offs=9) -- 3524(line=147, offs=11)
*/
ATSINSmove(tmp29, ATSSELcon(arg0, postiats_tysum_2, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3539(line=147, offs=26) -- 3544(line=147, offs=31)
*/
ATSINSmove(tmp30, PMVtmpltcst(g1int_add<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3529(line=147, offs=16) -- 3545(line=147, offs=32)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, ATSPMVrefarg0(tmp29)) ;
ATSINSmove_tlcal(argx1, tmp30) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSgoto(__patsflab_loop_11) ;
ATStailcalend()

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3548(line=148, offs=3) -- 3562(line=148, offs=17)
*/
__atstmplab6:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3429(line=141, offs=3) -- 3431(line=141, offs=5)
*/
#if(0)
if (ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3562(line=148, offs=17) -- 3562(line=148, offs=17)
*/
__atstmplab7:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3566(line=148, offs=21) -- 3567(line=148, offs=22)
*/
ATSINSmove(tmpret27, arg1) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret27) ;
} /* end of [loop_11__11] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3384(line=136, offs=16) -- 3655(line=156, offs=4)
*/
/*
local: 
global: list_vt_length$10$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(5646)
tmparg = S2Evar(a(5646))
tmpsub = Some(a(5646) -> S2Ecst(gene_type))
*/
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__list_vt_length__10__1(atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3369(line=136, offs=1) -- 3655(line=156, offs=4)
*/
__patsflab_list_vt_length:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3391(line=136, offs=23) -- 3655(line=156, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3639(line=155, offs=3) -- 3651(line=155, offs=15)
*/
ATSINSmove(tmpret26__1, loop_11__11__1(ATSPMVrefarg0(arg0), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3391(line=136, offs=23) -- 3655(line=156, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret26__1) ;
} /* end of [ATSLIB_056_prelude__list_vt_length__10__1] */

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3402(line=138, offs=5) -- 3574(line=150, offs=4)
*/
/*
local: loop_11$1(level=2)
global: loop_11$1(level=2)
local: 
global: 
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
loop_11__11__1(atsrefarg0_type(atstype_boxed) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atsrefarg0_type(atstype_boxed)) ;
ATStmpdec(argx1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret27__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp29__1, atstype_boxed) ;
ATStmpdec(tmp30__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3402(line=138, offs=5) -- 3574(line=150, offs=4)
*/
__patsflab_loop_11:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3487(line=145, offs=1) -- 3567(line=148, offs=22)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3501(line=146, offs=3) -- 3525(line=147, offs=12)
*/
__atstmplab4:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3429(line=141, offs=3) -- 3431(line=141, offs=5)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab7) ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3525(line=147, offs=12) -- 3525(line=147, offs=12)
*/
__atstmplab5:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3522(line=147, offs=9) -- 3524(line=147, offs=11)
*/
ATSINSmove(tmp29__1, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3539(line=147, offs=26) -- 3544(line=147, offs=31)
*/
ATSINSmove(tmp30__1, atspre_g1int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3529(line=147, offs=16) -- 3545(line=147, offs=32)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, ATSPMVrefarg0(tmp29__1)) ;
ATSINSmove_tlcal(argx1, tmp30__1) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSgoto(__patsflab_loop_11) ;
ATStailcalend()

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3548(line=148, offs=3) -- 3562(line=148, offs=17)
*/
__atstmplab6:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3429(line=141, offs=3) -- 3431(line=141, offs=5)
*/
#if(0)
if (ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3562(line=148, offs=17) -- 3562(line=148, offs=17)
*/
__atstmplab7:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 3566(line=148, offs=21) -- 3567(line=148, offs=22)
*/
ATSINSmove(tmpret27__1, arg1) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret27__1) ;
} /* end of [loop_11__11__1] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28132(line=758, offs=14) -- 28172(line=758, offs=54)
*/
/*
local: 
global: gt_g0int_int$16$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(4343)
tmparg = S2Evar(tk(4343))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__16(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret38, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp39, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28119(line=758, offs=1) -- 28172(line=758, offs=54)
*/
__patsflab_gt_g0int_int:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28158(line=758, offs=40) -- 28170(line=758, offs=52)
*/
ATSINSmove(tmp39, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4343))>)(arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28141(line=758, offs=23) -- 28172(line=758, offs=54)
*/
ATSINSmove(tmpret38, PMVtmpltcst(g0int_gt<S2Evar(tk(4343))>)(arg0, tmp39)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret38) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__16] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28132(line=758, offs=14) -- 28172(line=758, offs=54)
*/
/*
local: 
global: gt_g0int_int$16$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(4343)
tmparg = S2Evar(tk(4343))
tmpsub = Some(tk(4343) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__16__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret38__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp39__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28119(line=758, offs=1) -- 28172(line=758, offs=54)
*/
__patsflab_gt_g0int_int:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28158(line=758, offs=40) -- 28170(line=758, offs=52)
*/
ATSINSmove(tmp39__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/integer.dats: 28141(line=758, offs=23) -- 28172(line=758, offs=54)
*/
ATSINSmove(tmpret38__1, atspre_g0int_gt_int(arg0, tmp39__1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret38__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__16__1] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3332(line=175, offs=3) -- 3458(line=179, offs=2)
*/
/*
local: 
global: grcnflst_minmean_stdev$20$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_boxed
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grcnflst_minmean_stdev(atsrefarg0_type(atstype_boxed) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_type(atstype_ptrk) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret46, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3307(line=174, offs=1) -- 3458(line=179, offs=2)
*/
__patsflab_grcnflst_minmean_stdev:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3356(line=176, offs=1) -- 3458(line=179, offs=2)
*/
ATSINSmove(tmpret46, ATSLIB_056_prelude__list_vt_map_cloref__21__1(ATSPMVrefarg0(arg0), ATSPMVcfunlab(-1, __patsfun_29, (arg1, arg2)))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret46) ;
} /* end of [_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grcnflst_minmean_stdev] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15502(line=840, offs=3) -- 15701(line=850, offs=4)
*/
/*
local: 
global: list_vt_map_cloref$21$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = x(5833), y(5834)
tmparg = S2Evar(x(5833)); S2Evar(y(5834))
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_prelude__list_vt_map_cloref__21(atsrefarg0_type(atstype_boxed) arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret47, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15481(line=839, offs=1) -- 15701(line=850, offs=4)
*/
__patsflab_list_vt_map_cloref:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15512(line=840, offs=13) -- 15701(line=850, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15675(line=849, offs=3) -- 15696(line=849, offs=24)
*/
ATSINSmove(tmpret47, PMVtmpltcst(list_vt_map<S2Evar(x(5833))><S2Evar(y(5834))>)(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15512(line=840, offs=13) -- 15701(line=850, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret47) ;
} /* end of [ATSLIB_056_prelude__list_vt_map_cloref__21] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15555(line=844, offs=18) -- 15637(line=846, offs=4)
*/
/*
local: 
global: list_vt_map$fopr$22$0(level=1)
local: f$1588(1)(HSEfun(HSErefarg(1; HSEtyvar(x(5833))); HSEtyvar(y(5834))))
global: f$1588(1)(HSEfun(HSErefarg(1; HSEtyvar(x(5833))); HSEtyvar(y(5834))))
*/
ATSglobaldec()
/*
imparg = x2(5836), y2(5837)
tmparg = S2Evar(x2(5836)); S2Evar(y2(5837))
tmpsub = None()
*/
atstyvar_type(y2)
ATSLIB_056_prelude__list_vt_map__fopr__22(atstype_funptr env0, atsrefarg1_type(atstyvar_type(x2)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48, atstyvar_type(y2)) ;
ATStmpdec(tmp49, atstyvar_type(y)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15538(line=844, offs=1) -- 15637(line=846, offs=4)
*/
__patsflab_list_vt_map__fopr:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15562(line=844, offs=25) -- 15637(line=846, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15627(line=845, offs=62) -- 15631(line=845, offs=66)
*/
ATSINSmove(tmp49, ATSfunclo_clo(ATSPMVcastfn(cast, atstype_cloptr, env0), (atstype_cloptr, atsrefarg1_type(atstyvar_type(x2))), atstyvar_type(y))(ATSPMVcastfn(cast, atstype_cloptr, env0), ATSPMVrefarg1(arg0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15609(line=845, offs=44) -- 15631(line=845, offs=66)
*/
ATSINSmove(tmpret48, ATSPMVcastfn(castvwtp0, atstyvar_type(y2), tmp49)) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15562(line=844, offs=25) -- 15637(line=846, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret48) ;
} /* end of [ATSLIB_056_prelude__list_vt_map__fopr__22] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15502(line=840, offs=3) -- 15701(line=850, offs=4)
*/
/*
local: 
global: list_vt_map_cloref$21$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = x(5833), y(5834)
tmparg = S2Evar(x(5833)); S2Evar(y(5834))
tmpsub = Some(x(5833) -> S2Ecst(grcnf_vtype); y(5834) -> S2Ecst(expvar_type))
*/
atstype_boxed
ATSLIB_056_prelude__list_vt_map_cloref__21__1(atsrefarg0_type(atstype_boxed) arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret47__1, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15481(line=839, offs=1) -- 15701(line=850, offs=4)
*/
__patsflab_list_vt_map_cloref:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15512(line=840, offs=13) -- 15701(line=850, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15675(line=849, offs=3) -- 15696(line=849, offs=24)
*/
ATSINSmove(tmpret47__1, ATSLIB_056_prelude__list_vt_map__24__1(arg1, ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15512(line=840, offs=13) -- 15701(line=850, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret47__1) ;
} /* end of [ATSLIB_056_prelude__list_vt_map_cloref__21__1] */

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14519(line=786, offs=3) -- 15147(line=818, offs=4)
*/
/*
local: 
global: list_vt_map$24$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(5818), b(5819)
tmparg = S2Evar(a(5818)); S2Evar(b(5819))
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_prelude__list_vt_map__24(atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret51, atstype_boxed) ;
ATStmpdec(tmpref60, atstkind_type(atstype_ptrk)) ;
ATStmpdec_void(tmp61, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14505(line=785, offs=1) -- 15147(line=818, offs=4)
*/
__patsflab_list_vt_map:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14526(line=786, offs=10) -- 15147(line=818, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15099(line=813, offs=5) -- 15102(line=813, offs=8)
*/
/*
ATSINStmpdec(tmpref60) ;
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15117(line=814, offs=10) -- 15131(line=814, offs=24)
*/
ATSINSmove_void(tmp61, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$1575(1), flab=loop_25$0(level=1)), (atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstkind_type(atstype_ptrk))), atsvoid_t0ype)(ATSPMVrefarg0(arg0), ATSPMVrefarg1(ATSPMVptrof(tmpref60)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15140(line=817, offs=3) -- 15143(line=817, offs=6)
*/
ATSINSmove(tmpret51, tmpref60) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14526(line=786, offs=10) -- 15147(line=818, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret51) ;
} /* end of [ATSLIB_056_prelude__list_vt_map__24] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14576(line=790, offs=5) -- 15074(line=811, offs=4)
*/
/*
local: loop_25$0(level=1)
global: loop_25$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
loop_25__25(atsrefarg0_type(atstype_boxed) arg0, atsrefarg1_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret52, atsvoid_t0ype) ;
ATStmpdec(tmp55, atstyvar_type(b)) ;
ATStmpdec(tmp56, atstype_datcontyp) ;
ATStmpdec(tmp57, atstype_datcontyp) ;
ATStmpdec_void(tmp58, atsvoid_t0ype) ;
ATStmpdec(tmp59, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14576(line=790, offs=5) -- 15074(line=811, offs=4)
*/
__patsflab_loop_25:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14672(line=796, offs=3) -- 15070(line=810, offs=46)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14688(line=797, offs=5) -- 14716(line=798, offs=15)
*/
__atstmplab8:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14601(line=792, offs=3) -- 14603(line=792, offs=5)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab11) ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14716(line=798, offs=15) -- 14716(line=798, offs=15)
*/
__atstmplab9:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14720(line=798, offs=19) -- 14999(line=809, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14746(line=800, offs=9) -- 14771(line=800, offs=34)
*/
ATSINSmove(tmp55, PMVtmpltcst(list_vt_map$fopr<S2Evar(a(5818))><S2Evar(b(5819))>)(ATSPMVrefarg1(ATSPMVptrof(ATSSELcon(arg0, postiats_tysum_3, atslab__0))))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14817(line=802, offs=23) -- 14841(line=802, offs=47)
*/

ATSINSmove_con1(tmp56, postiats_tysum_4) ;
#if(0)
ATSINSstore_con_tag(tmp56, 0) ;
#endif
ATSINSstore_con_ofs(tmp56, postiats_tysum_4, atslab__0, tmp55) ;
#if(0)
ATSINSstore_con_ofs(tmp56, postiats_tysum_4, atslab__1, ATStop()) ;
#endif

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14810(line=802, offs=16) -- 14841(line=802, offs=47)
*/
ATSINSstore(ATSderef(arg1, atstkind_type(atstype_ptrk)), tmp56) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14877(line=803, offs=36) -- 14880(line=803, offs=39)
*/
ATSINSmove(tmp57, ATSderef(arg1, atstype_datcontyp)) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14852(line=803, offs=11) -- 14874(line=803, offs=33)
*/
#if(0)
if (ATSCKptrisnull(tmp57)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14896(line=804, offs=16) -- 14912(line=804, offs=32)
*/
ATSINSmove_void(tmp58, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$1575(1), flab=loop_25$0(level=1)), (atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstkind_type(atstype_ptrk))), atsvoid_t0ype)(ATSPMVrefarg0(ATSSELcon(arg0, postiats_tysum_3, atslab__1)), ATSPMVrefarg1(ATSPMVptrof(ATSSELcon(tmp57, postiats_tysum_5, atslab__1))))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14928(line=805, offs=16) -- 14937(line=805, offs=25)
*/
ATSINSmove_void(tmpret52, ATSempty()) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14720(line=798, offs=19) -- 14999(line=809, offs=8)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15029(line=810, offs=5) -- 15043(line=810, offs=19)
*/
__atstmplab10:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14601(line=792, offs=3) -- 14603(line=792, offs=5)
*/
#if(0)
if (ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15043(line=810, offs=19) -- 15043(line=810, offs=19)
*/
__atstmplab11:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15055(line=810, offs=31) -- 15069(line=810, offs=45)
*/

ATSINSmove_con0(tmp59, 0) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15048(line=810, offs=24) -- 15069(line=810, offs=45)
*/
ATSINSstore(ATSderef(arg1, atstkind_type(atstype_ptrk)), tmp59) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15048(line=810, offs=24) -- 15069(line=810, offs=45)
*/
ATSINSmove_void(tmpret52, ATSempty()) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn_void(tmpret52) ;
} /* end of [loop_25__25] */
#endif // end of [TEMPLATE]

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14519(line=786, offs=3) -- 15147(line=818, offs=4)
*/
/*
local: 
global: list_vt_map$24$1(level=2)
local: f$1588(1)(HSEfun(HSErefarg(1; HSEs2exp(S2Ecst(grcnf_vtype))); HSEs2exp(S2Ecst(expvar_type))))
global: f$1588(1)(HSEfun(HSErefarg(1; HSEs2exp(S2Ecst(grcnf_vtype))); HSEs2exp(S2Ecst(expvar_type))))
*/
ATSstaticdec()
/*
imparg = a(5818), b(5819)
tmparg = S2Evar(a(5818)); S2Evar(b(5819))
tmpsub = Some(a(5818) -> S2Ecst(grcnf_vtype); b(5819) -> S2Ecst(expvar_type))
*/
atstype_boxed
ATSLIB_056_prelude__list_vt_map__24__1(atstype_funptr env0, atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret51__1, atstype_boxed) ;
ATStmpdec(tmpref60__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec_void(tmp61__1, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14505(line=785, offs=1) -- 15147(line=818, offs=4)
*/
__patsflab_list_vt_map:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14526(line=786, offs=10) -- 15147(line=818, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15099(line=813, offs=5) -- 15102(line=813, offs=8)
*/
/*
ATSINStmpdec(tmpref60) ;
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15117(line=814, offs=10) -- 15131(line=814, offs=24)
*/
ATSINSmove_void(tmp61__1, loop_25__25__1(env0, ATSPMVrefarg0(arg0), ATSPMVrefarg1(ATSPMVptrof(tmpref60__1)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15140(line=817, offs=3) -- 15143(line=817, offs=6)
*/
ATSINSmove(tmpret51__1, tmpref60__1) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14526(line=786, offs=10) -- 15147(line=818, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret51__1) ;
} /* end of [ATSLIB_056_prelude__list_vt_map__24__1] */

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14576(line=790, offs=5) -- 15074(line=811, offs=4)
*/
/*
local: loop_25$1(level=3)
global: loop_25$1(level=3)
local: f$1588(1)(HSEfun(HSErefarg(1; HSEs2exp(S2Ecst(grcnf_vtype))); HSEs2exp(S2Ecst(expvar_type))))
global: f$1588(1)(HSEfun(HSErefarg(1; HSEs2exp(S2Ecst(grcnf_vtype))); HSEs2exp(S2Ecst(expvar_type))))
*/
ATSstaticdec()
atsvoid_t0ype
loop_25__25__1(atstype_funptr env0, atsrefarg0_type(atstype_boxed) arg0, atsrefarg1_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret52__1, atsvoid_t0ype) ;
ATStmpdec(tmp55__1, postiats_tyrec_0) ;
ATStmpdec(tmp56__1, atstype_datcontyp) ;
ATStmpdec(tmp57__1, atstype_datcontyp) ;
ATStmpdec_void(tmp58__1, atsvoid_t0ype) ;
ATStmpdec(tmp59__1, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14576(line=790, offs=5) -- 15074(line=811, offs=4)
*/
__patsflab_loop_25:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14672(line=796, offs=3) -- 15070(line=810, offs=46)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14688(line=797, offs=5) -- 14716(line=798, offs=15)
*/
__atstmplab8:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14601(line=792, offs=3) -- 14603(line=792, offs=5)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab11) ; }
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14716(line=798, offs=15) -- 14716(line=798, offs=15)
*/
__atstmplab9:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14720(line=798, offs=19) -- 14999(line=809, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14746(line=800, offs=9) -- 14771(line=800, offs=34)
*/
ATSINSmove(tmp55__1, ATSLIB_056_prelude__list_vt_map__fopr__22__1(env0, ATSPMVrefarg1(ATSPMVptrof(ATSSELcon(arg0, postiats_tysum_1, atslab__0))))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14817(line=802, offs=23) -- 14841(line=802, offs=47)
*/

ATSINSmove_con1(tmp56__1, postiats_tysum_6) ;
#if(0)
ATSINSstore_con_tag(tmp56__1, 0) ;
#endif
ATSINSstore_con_ofs(tmp56__1, postiats_tysum_6, atslab__0, tmp55__1) ;
#if(0)
ATSINSstore_con_ofs(tmp56__1, postiats_tysum_6, atslab__1, ATStop()) ;
#endif

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14810(line=802, offs=16) -- 14841(line=802, offs=47)
*/
ATSINSstore(ATSderef(arg1, atstkind_type(atstype_ptrk)), tmp56__1) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14877(line=803, offs=36) -- 14880(line=803, offs=39)
*/
ATSINSmove(tmp57__1, ATSderef(arg1, atstype_datcontyp)) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14852(line=803, offs=11) -- 14874(line=803, offs=33)
*/
#if(0)
if (ATSCKptrisnull(tmp57__1)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14896(line=804, offs=16) -- 14912(line=804, offs=32)
*/
ATSINSmove_void(tmp58__1, loop_25__25__1(env0, ATSPMVrefarg0(ATSSELcon(arg0, postiats_tysum_1, atslab__1)), ATSPMVrefarg1(ATSPMVptrof(ATSSELcon(tmp57__1, postiats_tysum_7, atslab__1))))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14928(line=805, offs=16) -- 14937(line=805, offs=25)
*/
ATSINSmove_void(tmpret52__1, ATSempty()) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14720(line=798, offs=19) -- 14999(line=809, offs=8)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15029(line=810, offs=5) -- 15043(line=810, offs=19)
*/
__atstmplab10:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 14601(line=792, offs=3) -- 14603(line=792, offs=5)
*/
#if(0)
if (ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15043(line=810, offs=19) -- 15043(line=810, offs=19)
*/
__atstmplab11:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15055(line=810, offs=31) -- 15069(line=810, offs=45)
*/

ATSINSmove_con0(tmp59__1, 0) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15048(line=810, offs=24) -- 15069(line=810, offs=45)
*/
ATSINSstore(ATSderef(arg1, atstkind_type(atstype_ptrk)), tmp59__1) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15048(line=810, offs=24) -- 15069(line=810, offs=45)
*/
ATSINSmove_void(tmpret52__1, ATSempty()) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn_void(tmpret52__1) ;
} /* end of [loop_25__25__1] */

/*
/home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15555(line=844, offs=18) -- 15637(line=846, offs=4)
*/
/*
local: 
global: list_vt_map$fopr$22$1(level=4)
local: f$1588(1)(HSEfun(HSErefarg(1; HSEs2exp(S2Ecst(grcnf_vtype))); HSEs2exp(S2Ecst(expvar_type))))
global: f$1588(1)(HSEfun(HSErefarg(1; HSEs2exp(S2Ecst(grcnf_vtype))); HSEs2exp(S2Ecst(expvar_type))))
*/
ATSstaticdec()
/*
imparg = x2(5836), y2(5837)
tmparg = S2Evar(x2(5836)); S2Evar(y2(5837))
tmpsub = Some(x(5833) -> S2Ecst(grcnf_vtype); y(5834) -> S2Ecst(expvar_type); x2(5836) -> S2Ecst(grcnf_vtype); y2(5837) -> S2Ecst(expvar_type))
*/
postiats_tyrec_0
ATSLIB_056_prelude__list_vt_map__fopr__22__1(atstype_funptr env0, atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48__1, postiats_tyrec_0) ;
ATStmpdec(tmp49__1, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15538(line=844, offs=1) -- 15637(line=846, offs=4)
*/
__patsflab_list_vt_map__fopr:
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15562(line=844, offs=25) -- 15637(line=846, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15627(line=845, offs=62) -- 15631(line=845, offs=66)
*/
ATSINSmove(tmp49__1, ATSfunclo_clo(ATSPMVcastfn(cast, atstype_cloptr, env0), (atstype_cloptr, atsrefarg1_type(atstkind_type(atstype_ptrk))), postiats_tyrec_0)(ATSPMVcastfn(cast, atstype_cloptr, env0), ATSPMVrefarg1(arg0))) ;

/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15609(line=845, offs=44) -- 15631(line=845, offs=66)
*/
ATSINSmove(tmpret48__1, ATSPMVcastfn(castvwtp0, postiats_tyrec_0, tmp49__1)) ;
/*
emit_instr: loc0 = /home/brand_000/ATS-Postiats/prelude/DATS/list_vt.dats: 15562(line=844, offs=25) -- 15637(line=846, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret48__1) ;
} /* end of [ATSLIB_056_prelude__list_vt_map__fopr__22__1] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3402(line=178, offs=11) -- 3456(line=178, offs=65)
*/
/*
local: 
global: __patsfun_29$0(level=1)
local: emap$3127(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), smap$3128(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: emap$3127(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), smap$3128(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
postiats_tyrec_0
__patsfun_29(atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) env1, atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret73, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3402(line=178, offs=11) -- 3456(line=178, offs=65)
*/
__patsflab___patsfun_29:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3417(line=178, offs=26) -- 3456(line=178, offs=65)
*/
ATSINSmove(tmpret73, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grcnf_minmean_stdev(ATSPMVrefarg0(ATSderef(arg0, atstkind_type(atstype_ptrk))), env0, env1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret73) ;
} /* end of [__patsfun_29] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3551(line=185, offs=3) -- 4291(line=225, offs=4)
*/
/*
local: 
global: grcnf_minmean_stdev$30$0(level=0)
local: 
global: 
*/
ATSglobaldec()
postiats_tyrec_0
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grcnf_minmean_stdev(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_type(atstype_ptrk) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret74, postiats_tyrec_0) ;
ATStmpdec(tmpref84, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmpref85, atstkind_t0ype(atstype_double)) ;
ATStmpdec_void(tmp86, atsvoid_t0ype) ;
ATStmpdec_void(tmp87, atsvoid_t0ype) ;
ATStmpdec(tmp88, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp89, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp90, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3529(line=184, offs=1) -- 4291(line=225, offs=4)
*/
__patsflab_grcnf_minmean_stdev:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3573(line=185, offs=25) -- 4291(line=225, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4053(line=214, offs=5) -- 4057(line=214, offs=9)
*/
/*
ATSINStmpdec(tmpref84) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4068(line=214, offs=20) -- 4071(line=214, offs=23)
*/
ATSINSmove(tmpref84, ATSextval(INFINITY)) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4076(line=215, offs=5) -- 4081(line=215, offs=10)
*/
/*
ATSINStmpdec(tmpref85) ;
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4092(line=215, offs=21) -- 4095(line=215, offs=24)
*/
ATSINSmove(tmpref85, atspre_g0float_div_double(ATSPMVf0loat(0.0), ATSPMVf0loat(0.0))) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4149(line=219, offs=10) -- 4172(line=219, offs=33)
*/
ATSINSmove_void(tmp86, loop_31(arg1, arg2, ATSPMVrefarg0(ATSPMVcastfn(castvwtp1, atstype_boxed, ATSPMVrefarg0(arg0))), ATSPMVrefarg1(ATSPMVptrof(tmpref84)), ATSPMVrefarg1(ATSPMVptrof(tmpref85)))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4215(line=221, offs=13) -- 4225(line=221, offs=23)
*/
ATSINSmove(tmp88, atspre_g0float_eq_double(tmpref84, ATSextval(INFINITY))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4212(line=221, offs=10) -- 4242(line=221, offs=40)
*/
ATSif(
tmp88
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4239(line=221, offs=37) -- 4242(line=221, offs=40)
*/
ATSINSmove(tmp89, atspre_g0float_div_double(ATSPMVf0loat(0.0), ATSPMVf0loat(0.0))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4231(line=221, offs=29) -- 4242(line=221, offs=40)
*/
ATSINSstore(tmpref84, tmp89) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4231(line=221, offs=29) -- 4242(line=221, offs=40)
*/
ATSINSmove_void(tmp87, ATSempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4242(line=221, offs=40) -- 4242(line=221, offs=40)
*/
ATSINSmove_void(tmp87, ATSempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4272(line=224, offs=22) -- 4285(line=224, offs=35)
*/
ATSINSmove(tmp90, atslib_sqrt_double(tmpref85)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4253(line=224, offs=3) -- 4287(line=224, offs=37)
*/
ATSINSmove(tmpret74, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_make(tmpref84, tmp90)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3573(line=185, offs=25) -- 4291(line=225, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret74) ;
} /* end of [_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__grcnf_minmean_stdev] */

/*
/cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3688(line=195, offs=5) -- 4045(line=212, offs=2)
*/
/*
local: loop_31$0(level=1)
global: loop_31$0(level=1)
local: emap$3131(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), smap$3132(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: emap$3131(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), smap$3132(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atsvoid_t0ype
loop_31(atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) env1, atsrefarg0_type(atstype_boxed) arg0, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg1, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atsrefarg0_type(atstype_boxed)) ;
ATStmpdec(argx1, atsrefarg1_type(atstkind_t0ype(atstype_double))) ;
ATStmpdec(argx2, atsrefarg1_type(atstkind_t0ype(atstype_double))) ;
ATStmpdec_void(tmpret75, atsvoid_t0ype) ;
ATStmpdec(tmp76, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp77, atstype_boxed) ;
ATStmpdec(tmp78, postiats_tyrec_0) ;
ATStmpdec_void(tmp79, atsvoid_t0ype) ;
ATStmpdec(tmp80, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp81, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp82, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp83, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3688(line=195, offs=5) -- 4045(line=212, offs=2)
*/
__patsflab_loop_31:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3769(line=201, offs=3) -- 4043(line=211, offs=25)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3786(line=202, offs=5) -- 3814(line=203, offs=16)
*/
__atstmplab12:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3697(line=197, offs=3) -- 3700(line=197, offs=6)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab15) ; }
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3814(line=203, offs=16) -- 3814(line=203, offs=16)
*/
__atstmplab13:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3806(line=203, offs=8) -- 3808(line=203, offs=10)
*/
ATSINSmove(tmp76, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3810(line=203, offs=12) -- 3813(line=203, offs=15)
*/
ATSINSmove(tmp77, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3818(line=203, offs=20) -- 3998(line=210, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3843(line=205, offs=7) -- 3873(line=205, offs=37)
*/
ATSINSmove(tmp78, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__genes_meanvar(ATSPMVrefarg0(tmp76), env0, env1)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3898(line=207, offs=10) -- 3905(line=207, offs=17)
*/
ATSINSmove(tmp81, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_get_exp(tmp78)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3898(line=207, offs=10) -- 3912(line=207, offs=24)
*/
ATSINSmove(tmp80, atspre_g0float_lt_double(tmp81, ATSderef(arg1, atstkind_t0ype(atstype_double)))) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3895(line=207, offs=7) -- 3953(line=207, offs=65)
*/
ATSif(
tmp80
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3927(line=207, offs=39) -- 3934(line=207, offs=46)
*/
ATSINSmove(tmp82, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_get_exp(tmp78)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3919(line=207, offs=31) -- 3934(line=207, offs=46)
*/
ATSINSstore(ATSderef(arg1, atstkind_t0ype(atstype_double)), tmp82) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3945(line=207, offs=57) -- 3952(line=207, offs=64)
*/
ATSINSmove(tmp83, _057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_056_sats__expvar_get_var(tmp78)) ;

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3936(line=207, offs=48) -- 3952(line=207, offs=64)
*/
ATSINSstore(ATSderef(arg2, atstkind_t0ype(atstype_double)), tmp83) ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3936(line=207, offs=48) -- 3952(line=207, offs=64)
*/
ATSINSmove_void(tmp79, ATSempty()) ;
} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3953(line=207, offs=65) -- 3953(line=207, offs=65)
*/
ATSINSmove_void(tmp79, ATSempty()) ;
} /* ATSendif */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3967(line=209, offs=7) -- 3990(line=209, offs=30)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, ATSPMVrefarg0(tmp77)) ;
ATSINSmove_tlcal(argx1, ATSPMVrefarg1(arg1)) ;
ATSINSmove_tlcal(argx2, ATSPMVrefarg1(arg2)) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSINSargmove_tlcal(arg2, argx2) ;
ATSgoto(__patsflab_loop_31) ;
ATStailcalend()

/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3818(line=203, offs=20) -- 3998(line=210, offs=8)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4023(line=211, offs=5) -- 4037(line=211, offs=19)
*/
__atstmplab14:
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 3697(line=197, offs=3) -- 3700(line=197, offs=6)
*/
#if(0)
if (ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4037(line=211, offs=19) -- 4037(line=211, offs=19)
*/
__atstmplab15:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/cygwin/home/brand_000/FBA/FALCON/GPR/falcon_algorithm1.dats: 4041(line=211, offs=23) -- 4043(line=211, offs=25)
*/
ATSINSmove_void(tmpret75, ATSempty()) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn_void(tmpret75) ;
} /* end of [loop_31] */

/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__dynload()
{
ATSdynload1(
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_cygdrive_057_c_057_cygwin_057_home_057_brand_000_057_FBA_057_FALCON_057_GPR_057_falcon_algorithm1_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
